"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
    CONTROL_SETUP: "when program starts",
    CONTROL_FOREVER: "forever",
    CONTROL_REPEAT: "repeat %1",
    CONTROL_IF: "if %1 then",
    CONTROL_ELSE: "else",
    CONTROL_STOP: "stop",
    CONTROL_STOP_ALL: "all",
    CONTROL_STOP_THIS: "this script",
    CONTROL_STOP_OTHER: "other scripts in sprite",
    CONTROL_WAIT: "wait %1 seconds",
    CONTROL_WAITUNTIL: "wait until %1",
    CONTROL_REPEATUNTIL: "repeat until %1",
    CONTROL_WHILE: "while %1",
    CONTROL_FOREACH: "for each %1 in %2",
    CONTROL_STARTASCLONE: "when I start as a clone",
    CONTROL_CREATECLONEOF: "create clone of %1",
    CONTROL_CREATECLONEOF_MYSELF: "myself",
    CONTROL_DELETETHISCLONE: "delete this clone",
    CONTROL_COUNTER: "counter",
    CONTROL_INCRCOUNTER: "increment counter",
    CONTROL_CLEARCOUNTER: "clear counter",
    CONTROL_ALLATONCE: "all at once",
    DATA_SETVARIABLETO: "set %1 to %2",
    DATA_CHANGEVARIABLEBY: "change %1 by %2",
    DATA_SHOWVARIABLE: "show variable %1",
    DATA_HIDEVARIABLE: "hide variable %1",
    DATA_ADDTOLIST: "add %1 to %2",
    DATA_DELETEOFLIST: "delete %1 of %2",
    DATA_DELETEALLOFLIST: "delete all of %1",
    DATA_INSERTATLIST: "insert %1 at %2 of %3",
    DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
    DATA_ITEMOFLIST: "item %1 of %2",
    DATA_ITEMNUMOFLIST: "item # of %1 in %2",
    DATA_LENGTHOFLIST: "length of %1",
    DATA_LISTCONTAINSITEM: "%1 contains %2?",
    DATA_SHOWLIST: "show list %1",
    DATA_HIDELIST: "hide list %1",
    DATA_INDEX_ALL: "all",
    DATA_INDEX_LAST: "last",
    DATA_INDEX_RANDOM: "random",
    EVENT_WHENFLAGCLICKED: "when %1 clicked",
    EVENT_WHENTHISSPRITECLICKED: "when this sprite clicked",
    EVENT_WHENSTAGECLICKED: "when stage clicked",
    EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
    EVENT_WHENBROADCASTRECEIVED: "when I receive %1",
    EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
    EVENT_WHENGREATERTHAN: "when %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "timer",
    EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
    EVENT_BROADCAST: "broadcast %1",
    EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
    EVENT_WHENKEYPRESSED: "when %1 key pressed",
    EVENT_WHENKEYPRESSED_SPACE: "space",
    EVENT_WHENKEYPRESSED_LEFT: "left arrow",
    EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
    EVENT_WHENKEYPRESSED_DOWN: "down arrow",
    EVENT_WHENKEYPRESSED_UP: "up arrow",
    EVENT_WHENKEYPRESSED_ANY: "any",
    LOOKS_SAYFORSECS: "say %1 for %2 seconds",
    LOOKS_SAY: "say %1",
    LOOKS_HELLO: "Hello!",
    LOOKS_THINKFORSECS: "think %1 for %2 seconds",
    LOOKS_THINK: "think %1",
    LOOKS_HMM: "Hmm...",
    LOOKS_SHOW: "show",
    LOOKS_HIDE: "hide",
    LOOKS_HIDEALLSPRITES: "hide all sprites",
    LOOKS_EFFECT_COLOR: "color",
    LOOKS_EFFECT_FISHEYE: "fisheye",
    LOOKS_EFFECT_WHIRL: "whirl",
    LOOKS_EFFECT_PIXELATE: "pixelate",
    LOOKS_EFFECT_MOSAIC: "mosaic",
    LOOKS_EFFECT_BRIGHTNESS: "brightness",
    LOOKS_EFFECT_GHOST: "ghost",
    LOOKS_CHANGEEFFECTBY: "change %1 effect by %2",
    LOOKS_SETEFFECTTO: "set %1 effect to %2",
    LOOKS_CLEARGRAPHICEFFECTS: "clear graphic effects",
    LOOKS_CHANGESIZEBY: "change size by %1",
    LOOKS_SETSIZETO: "set size to %1 %",
    LOOKS_SIZE: "size",
    LOOKS_CHANGESTRETCHBY: "change stretch by %1",
    LOOKS_SETSTRETCHTO: "set stretch to %1 %",
    LOOKS_SWITCHCOSTUMETO: "switch costume to %1",
    LOOKS_NEXTCOSTUME: "next costume",
    LOOKS_SWITCHBACKDROPTO: "switch backdrop to %1",
    LOOKS_GOTOFRONTBACK: "go to %1 layer",
    LOOKS_GOTOFRONTBACK_FRONT: "front",
    LOOKS_GOTOFRONTBACK_BACK: "back",
    LOOKS_GOFORWARDBACKWARDLAYERS: "go %1 %2 layers",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "forward",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "backward",
    LOOKS_BACKDROPNUMBERNAME: "backdrop %1",
    LOOKS_COSTUMENUMBERNAME: "costume %1",
    LOOKS_NUMBERNAME_NUMBER: "number",
    LOOKS_NUMBERNAME_NAME: "name",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "switch backdrop to %1 and wait",
    LOOKS_NEXTBACKDROP_BLOCK: "next backdrop",
    LOOKS_NEXTBACKDROP: "next backdrop",
    LOOKS_PREVIOUSBACKDROP: "previous backdrop",
    LOOKS_RANDOMBACKDROP: "random backdrop",
    MOTION_MOVESTEPS: "move %1 steps",
    MOTION_TURNLEFT: "turn %1 %2 degrees",
    MOTION_TURNRIGHT: "turn %1 %2 degrees",
    MOTION_POINTINDIRECTION: "point in direction %1",
    MOTION_POINTTOWARDS: "point towards %1",
    MOTION_POINTTOWARDS_POINTER: "mouse-pointer",
    MOTION_POINTTOWARDS_RANDOM: "random direction",
    MOTION_GOTO: "go to %1",
    MOTION_GOTO_POINTER: "mouse-pointer",
    MOTION_GOTO_RANDOM: "random position",
    MOTION_GOTOXY: "go to x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "glide %1 secs to x: %2 y: %3",
    MOTION_GLIDETO: "glide %1 secs to %2",
    MOTION_GLIDETO_POINTER: "mouse-pointer",
    MOTION_GLIDETO_RANDOM: "random position",
    MOTION_CHANGEXBY: "change x by %1",
    MOTION_SETX: "set x to %1",
    MOTION_CHANGEYBY: "change y by %1",
    MOTION_SETY: "set y to %1",
    MOTION_IFONEDGEBOUNCE: "if on edge, bounce",
    MOTION_SETROTATIONSTYLE: "set rotation style %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "left-right",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "don't rotate",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "all around",
    MOTION_XPOSITION: "x position",
    MOTION_YPOSITION: "y position",
    MOTION_DIRECTION: "direction",
    MOTION_SCROLLRIGHT: "scroll right %1",
    MOTION_SCROLLUP: "scroll up %1",
    MOTION_ALIGNSCENE: "align scene %1",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "bottom-left",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "bottom-right",
    MOTION_ALIGNSCENE_MIDDLE: "middle",
    MOTION_ALIGNSCENE_TOPLEFT: "top-left",
    MOTION_ALIGNSCENE_TOPRIGHT: "top-right",
    MOTION_XSCROLL: "x scroll",
    MOTION_YSCROLL: "y scroll",
    MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "pick random %1 to %2",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 and %2",
    OPERATORS_OR: "%1 or %2",
    OPERATORS_NOT: "not %1",
    OPERATORS_JOIN: "join %1 and %2",
    OPERATORS_JOIN_THREE: "join %1 and %2 and %3",
    OPERATORS_CONSTRAINS: "Constrains %1 in Min:%2 Max:%3",
    OPERATORS_JOIN_APPLE: "apple",
    OPERATORS_JOIN_BANANA: "banana",
    OPERATORS_LETTEROF: "letter %1 of %2",
    OPERATORS_LETTEROF_APPLE: "a",
    OPERATORS_LENGTH: "length of %1",
    OPERATORS_CONTAINS: "%1 contains %2?",
    OPERATORS_MOD: "%1 mod %2",
    OPERATORS_ROUND: "round %1",
    OPERATORS_MATHOP: "%1 of %2",
    OPERATORS_MATHOP_ABS: "abs",
    OPERATORS_MATHOP_FLOOR: "floor",
    OPERATORS_MATHOP_CEILING: "ceiling",
    OPERATORS_MATHOP_SQRT: "sqrt",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
    OPERATORS_TOSTRING: "%1 to String",
    PROCEDURES_DEFINITION: "define %1",
    SENSING_TOUCHINGOBJECT: "touching %1?",
    SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
    SENSING_TOUCHINGOBJECT_EDGE: "edge",
    SENSING_TOUCHINGCOLOR: "touching color %1?",
    SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
    SENSING_DISTANCETO: "distance to %1",
    SENSING_DISTANCETO_POINTER: "mouse-pointer",
    SENSING_ASKANDWAIT: "ask %1 and wait",
    SENSING_ASK_TEXT: "What's your name?",
    SENSING_ANSWER: "answer",
    SENSING_KEYPRESSED: "key %1 pressed?",
    SENSING_MOUSEDOWN: "mouse down?",
    SENSING_MOUSEX: "mouse x",
    SENSING_MOUSEY: "mouse y",
    SENSING_SETDRAGMODE: "set drag mode %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
    SENSING_LOUDNESS: "loudness",
    SENSING_LOUD: "loud?",
    SENSING_TIMER: "timer",
    SENSING_RESETTIMER: "reset timer",
    SENSING_OF: "%1 of %2",
    SENSING_OF_XPOSITION: "x position",
    SENSING_OF_YPOSITION: "y position",
    SENSING_OF_DIRECTION: "direction",
    SENSING_OF_COSTUMENUMBER: "costume #",
    SENSING_OF_COSTUMENAME: "costume name",
    SENSING_OF_SIZE: "size",
    SENSING_OF_VOLUME: "volume",
    SENSING_OF_BACKDROPNUMBER: "backdrop #",
    SENSING_OF_BACKDROPNAME: "backdrop name",
    SENSING_OF_STAGE: "Stage",
    SENSING_CURRENT: "current %1",
    SENSING_CURRENT_YEAR: "year",
    SENSING_CURRENT_MONTH: "month",
    SENSING_CURRENT_DATE: "date",
    SENSING_CURRENT_DAYOFWEEK: "day of week",
    SENSING_CURRENT_HOUR: "hour",
    SENSING_CURRENT_MINUTE: "minute",
    SENSING_CURRENT_SECOND: "second",
    SENSING_DAYSSINCE2000: "days since 2000",
    SENSING_USERNAME: "username",
    SENSING_USERID: "user id",
    SOUND_PLAY: "start sound %1",
    SOUND_PLAYUNTILDONE: "play sound %1 until done",
    SOUND_STOPALLSOUNDS: "stop all sounds",
    SOUND_SETEFFECTO: "set %1 effect to %2",
    SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
    SOUND_CLEAREFFECTS: "clear sound effects",
    SOUND_EFFECTS_PITCH: "pitch",
    SOUND_EFFECTS_PAN: "pan left/right",
    SOUND_CHANGEVOLUMEBY: "change volume by %1",
    SOUND_SETVOLUMETO: "set volume to %1%",
    SOUND_VOLUME: "volume",
    SOUND_RECORD: "record...",
    CATEGORY_MOTION: "Motor",
    CATEGORY_MOVEMENT: "Movement",
    CATEGORY_LOOKS: "Display",
    CATEGORY_SOUND: "Sound",
    CATEGORY_EVENTS: "Events",
    CATEGORY_CONTROL: "Control",
    CATEGORY_SENSING: "Sensors",
    CATEGORY_OPERATORS: "Operators",
    CATEGORY_VARIABLES: "Variables",
    CATEGORY_MYBLOCKS: "My Blocks",
    DUPLICATE: "Duplicate",
    DELETE: "Delete",
    ADD_COMMENT: "Add Comment",
    REMOVE_COMMENT: "Remove Comment",
    DELETE_BLOCK: "Delete Block",
    DELETE_X_BLOCKS: "Delete %1 Blocks",
    DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
    CLEAN_UP: "Clean up Blocks",
    HELP: "Help",
    UNDO: "Undo",
    REDO: "Redo",
    EDIT_PROCEDURE: "Edit",
    SHOW_PROCEDURE_DEFINITION: "Go to definition",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
    COLOUR_HUE_LABEL: "Color",
    COLOUR_SATURATION_LABEL: "Saturation",
    COLOUR_BRIGHTNESS_LABEL: "Brightness",
    CHANGE_VALUE_TITLE: "Change value:",
    RENAME_VARIABLE: "Rename variable",
    RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
    RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
    NEW_VARIABLE: "Make a Variable",
    NEW_VARIABLE_TITLE: "New variable name:",
    VARIABLE_MODAL_TITLE: "New Variable",
    VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: 'A variable named "%1" already exists for another variable of type "%2".',
    DELETE_VARIABLE_CONFIRMATION: 'Delete %1 uses of the "%2" variable?',
    CANNOT_DELETE_VARIABLE_PROCEDURE: 'Can\'t delete the variable "%1" because it\'s part of the definition of the function "%2"',
    DELETE_VARIABLE: 'Delete the "%1" variable',
    NEW_PROCEDURE: "Make a Block",
    PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "To delete a block definition, first remove all uses of the block",
    NEW_LIST: "Make a List",
    NEW_LIST_TITLE: "New list name:",
    LIST_MODAL_TITLE: "New List",
    LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
    RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
    RENAME_LIST_MODAL_TITLE: "Rename List",
    DEFAULT_LIST_ITEM: "thing",
    DELETE_LIST: 'Delete the "%1" list',
    RENAME_LIST: "Rename list",
    NEW_BROADCAST_MESSAGE: "New message",
    NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
    BROADCAST_MODAL_TITLE: "New Message",
    DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
    // Sound category
    NXT_BUZZER_TONE: "Play beep %1 Hz for %2 seconds",
    NXT_BUZZER_NOTE: "Play note %1 for %2 seconds",
    NXT_BUZZER_STOP: "Stop all sounds",
    
    // Display category
    NXT_DISP_PRINTCOL: "Write %1 at Col%2 Line%3",
    NXT_DISP_CLEAR: "Clear display",
    
    // Motor category
    NXT_MOTOR_RUNFOR: "%1 run for %2 %3 at %4% speed",
    NXT_MOTOR_ON: "%1 start motor at %2% speed",
    NXT_MOTOR_OFF: "%1 stop motor",
    NXT_MOTOR_RESET: "%1 reset degrees counted",
    NXT_MOTOR_DEGREES: "%1 degrees counted",
    
    // Movement category
    NXT_MOVE_SETTING: "Set movement motor to %1 and %2",
    NXT_MOVE_RUNFOR: "Move for %1 %2 at %3% %4% speed",
    NXT_MOVE_ON: "Start moving at %1% %2% speed",
    NXT_MOVE_OFF: "Stop moving",
    
    // Sensor category
    NXT_SENSORS_LIGHT_RFL: "%1 reflected light intensity",
    NXT_SENSORS_LIGHT_AMB: "%1 ambient light intensity",
    NXT_SENSORS_US: "%1 distance in cm",
    NXT_SENSORS_SOUND: "%1 sound level",
    NXT_SENSORS_TOUCH: "%1 is pressed?",
    NXT_SENSORS_BUTTON: "is %1 button pressed?",
    NXT_SENSORS_TIMER: "Timer (secs)",
    NXT_SENSORS_TIMER_RESET: "Reset timer",
    
    // Dropdown options
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",
    
    NXT_UNIT_ROTATIONS: "rotations",
    NXT_UNIT_DEGREES: "degrees",
    NXT_UNIT_SECONDS: "seconds",
    
    NXT_BUTTON_LEFT: "Left",
    NXT_BUTTON_CENTER: "Center",
    NXT_BUTTON_RIGHT: "Right"
};

Blockly.ScratchMsgs.locales["zh-tw"] = {
    CONTROL_SETUP: "當程式開始時",
    CONTROL_FOREVER: "重複執行",
    CONTROL_REPEAT: "重複執行 %1 次",
    CONTROL_IF: "如果 %1 那麼",
    CONTROL_ELSE: "否則",
    CONTROL_STOP: "停止",
    CONTROL_STOP_ALL: "全部腳本",
    CONTROL_STOP_THIS: "這個腳本",
    CONTROL_STOP_OTHER: "該角色的其他腳本",
    CONTROL_WAIT: "等待 %1 秒",
    CONTROL_WAITUNTIL: "等待 %1",
    CONTROL_REPEATUNTIL: "重複執行直到 %1",
    CONTROL_WHILE: "當 %1 重複執行",
    CONTROL_FOREACH: "對於 %2 中的每個 %1",
    CONTROL_STARTASCLONE: "當作為克隆體啟動時",
    CONTROL_CREATECLONEOF: "克隆 %1",
    CONTROL_CREATECLONEOF_MYSELF: "自己",
    CONTROL_DELETETHISCLONE: "刪除此複製體",
    CONTROL_COUNTER: "計數器",
    CONTROL_INCRCOUNTER: "計數器加一",
    CONTROL_CLEARCOUNTER: "計數器歸零",
    CONTROL_ALLATONCE: "所有腳本",
    DATA_SETVARIABLETO: "將 %1 設為 %2",
    DATA_CHANGEVARIABLEBY: "增加 %1 %2",
    DATA_SHOWVARIABLE: "顯示變數 %1",
    DATA_HIDEVARIABLE: "隱藏變數 %1",
    DATA_ADDTOLIST: "將 %1 加入 %2",
    DATA_DELETEOFLIST: "刪除 %2 的第 %1 項",
    DATA_DELETEALLOFLIST: "刪除 %1 的全部項目",
    DATA_INSERTATLIST: "在 %3 的第 %2 項前插入 %1",
    DATA_REPLACEITEMOFLIST: "將 %2 的第 %1 項替換為 %3",
    DATA_ITEMOFLIST: "%2 的第 %1 項",
    DATA_ITEMNUMOFLIST: "%2 中第一個 %1 的編號",
    DATA_LENGTHOFLIST: "%1 的項目數",
    DATA_LISTCONTAINSITEM: "%1 包含 %2 ?",
    DATA_SHOWLIST: "顯示清單 %1",
    DATA_HIDELIST: "隱藏清單 %1",
    DATA_INDEX_ALL: "全部",
    DATA_INDEX_LAST: "結尾",
    DATA_INDEX_RANDOM: "隨機",
    EVENT_WHENFLAGCLICKED: "當 %1 被點擊",
    EVENT_WHENTHISSPRITECLICKED: "當角色被點擊",
    EVENT_WHENSTAGECLICKED: "當舞台點擊",
    EVENT_WHENTOUCHINGOBJECT: "當角色碰到 %1",
    EVENT_WHENBROADCASTRECEIVED: "當接收到 %1",
    EVENT_WHENBACKDROPSWITCHESTO: "當背景換成 %1",
    EVENT_WHENGREATERTHAN: "當 %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "計時器",
    EVENT_WHENGREATERTHAN_LOUDNESS: "響度",
    EVENT_BROADCAST: "廣播 %1",
    EVENT_BROADCASTANDWAIT: "廣播 %1 並等待",
    EVENT_WHENKEYPRESSED: "當按下 %1 鍵",
    EVENT_WHENKEYPRESSED_SPACE: "空格",
    EVENT_WHENKEYPRESSED_LEFT: "←",
    EVENT_WHENKEYPRESSED_RIGHT: "→",
    EVENT_WHENKEYPRESSED_DOWN: "↓",
    EVENT_WHENKEYPRESSED_UP: "↑",
    EVENT_WHENKEYPRESSED_ANY: "任意",
    LOOKS_SAYFORSECS: "說 %1 %2 秒",
    LOOKS_SAY: "說 %1",
    LOOKS_HELLO: "你好！",
    LOOKS_THINKFORSECS: "思考 %1 %2 秒",
    LOOKS_THINK: "思考 %1",
    LOOKS_HMM: "嗯…",
    LOOKS_SHOW: "顯示",
    LOOKS_HIDE: "隱藏",
    LOOKS_HIDEALLSPRITES: "隱藏所有角色",
    LOOKS_EFFECT_COLOR: "顏色",
    LOOKS_EFFECT_FISHEYE: "魚眼",
    LOOKS_EFFECT_WHIRL: "漩渦",
    LOOKS_EFFECT_PIXELATE: "像素化",
    LOOKS_EFFECT_MOSAIC: "馬賽克",
    LOOKS_EFFECT_BRIGHTNESS: "亮度",
    LOOKS_EFFECT_GHOST: "虛像",
    LOOKS_CHANGEEFFECTBY: "將 %1 特效增加 %2",
    LOOKS_SETEFFECTTO: "將 %1 特效設定為 %2",
    LOOKS_CLEARGRAPHICEFFECTS: "清除圖形特效",
    LOOKS_CHANGESIZEBY: "將大小增加 %1",
    LOOKS_SETSIZETO: "將大小設為 %1",
    LOOKS_SIZE: "大小",
    LOOKS_CHANGESTRETCHBY: "伸縮%1",
    LOOKS_SETSTRETCHTO: "設定伸縮為%1 %",
    LOOKS_SWITCHCOSTUMETO: "換成 %1 造型",
    LOOKS_NEXTCOSTUME: "下一個造型",
    LOOKS_SWITCHBACKDROPTO: "換成 %1 背景",
    LOOKS_GOTOFRONTBACK: "移到最 %1 ",
    LOOKS_GOTOFRONTBACK_FRONT: "前面",
    LOOKS_GOTOFRONTBACK_BACK: "後面",
    LOOKS_GOFORWARDBACKWARDLAYERS: "%1 %2 層",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "前移",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "後移",
    LOOKS_BACKDROPNUMBERNAME: "背景 %1",
    LOOKS_COSTUMENUMBERNAME: "造型 %1",
    LOOKS_NUMBERNAME_NUMBER: "編號",
    LOOKS_NUMBERNAME_NAME: "名稱",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "換成 %1 背景並等待",
    LOOKS_NEXTBACKDROP_BLOCK: "下一個背景",
    LOOKS_NEXTBACKDROP: "下一個背景",
    LOOKS_PREVIOUSBACKDROP: "上一個背景",
    LOOKS_RANDOMBACKDROP: "隨機背景",
    MOTION_MOVESTEPS: "移動 %1 步驟",
    MOTION_TURNLEFT: "左轉 %1 %2 度",
    MOTION_TURNRIGHT: "右轉 %1 %2 度",
    MOTION_POINTINDIRECTION: "面向 %1 方向",
    MOTION_POINTTOWARDS: "面向 %1",
    MOTION_POINTTOWARDS_POINTER: "滑鼠指標",
    MOTION_POINTTOWARDS_RANDOM: "隨機方向",
    MOTION_GOTO: "移到 %1",
    MOTION_GOTO_POINTER: "滑鼠指標",
    MOTION_GOTO_RANDOM: "隨機位置",
    MOTION_GOTOXY: "移到 x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "在 %1 秒內滑到 x: %2 y: %3",
    MOTION_GLIDETO: "在 %1 秒內滑到 %2",
    MOTION_GLIDETO_POINTER: "滑鼠指標",
    MOTION_GLIDETO_RANDOM: "隨機位置",
    MOTION_CHANGEXBY: "將x座標增加 %1",
    MOTION_SETX: "將x座標設為 %1",
    MOTION_CHANGEYBY: "將y座標增加 %1",
    MOTION_SETY: "將y座標設為 %1",
    MOTION_IFONEDGEBOUNCE: "碰到邊緣就反彈",
    MOTION_SETROTATIONSTYLE: "將旋轉方式設為 %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "左右翻轉",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "不可旋轉",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "任意旋轉",
    MOTION_XPOSITION: "x 座標",
    MOTION_YPOSITION: "y 座標",
    MOTION_DIRECTION: "方向",
    MOTION_SCROLLRIGHT: "向右捲動 %1",
    MOTION_SCROLLUP: "向上捲動 %1",
    MOTION_ALIGNSCENE: "與場景 %1 對齊",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "左下角",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "右下角",
    MOTION_ALIGNSCENE_MIDDLE: "中間",
    MOTION_ALIGNSCENE_TOPLEFT: "左上角",
    MOTION_ALIGNSCENE_TOPRIGHT: "右上角",
    MOTION_XSCROLL: "x滾動位置",
    MOTION_YSCROLL: "y滾動位置",
    MOTION_STAGE_SELECTED: "選中了舞台：不可使用運動類積木",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "在 %1 和 %2 之間取隨機數",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 且 %2",
    OPERATORS_OR: "%1 或 %2",
    OPERATORS_NOT: "%1 不成立",
    OPERATORS_JOIN: "連接 %1 和 %2",
    OPERATORS_JOIN_THREE: "連接 %1 和 %2 和 %3",
    OPERATORS_CONSTRAINS: "限制%1在最小:%2 最大:%3之間",
    OPERATORS_JOIN_APPLE: "蘋果",
    OPERATORS_JOIN_BANANA: "香蕉",
    OPERATORS_LETTEROF: "%2 的第 %1 個字元",
    OPERATORS_LETTEROF_APPLE: "果實",
    OPERATORS_LENGTH: "%1 的字元數",
    OPERATORS_CONTAINS: "%1 包含 %2 ?",
    OPERATORS_MOD: "%1 除以 %2 的餘數",
    OPERATORS_ROUND: "四捨五入 %1",
    OPERATORS_MATHOP: "%1 %2",
    OPERATORS_MATHOP_ABS: "絕對值",
    OPERATORS_MATHOP_FLOOR: "向下取整",
    OPERATORS_MATHOP_CEILING: "向上取整",
    OPERATORS_MATHOP_SQRT: "平方根",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
    OPERATORS_TOSTRING: "%1 轉為字串",
    PROCEDURES_DEFINITION: "定義 %1",
    SENSING_TOUCHINGOBJECT: "碰到 %1 ?",
    SENSING_TOUCHINGOBJECT_POINTER: "滑鼠指標",
    SENSING_TOUCHINGOBJECT_EDGE: "舞台邊緣",
    SENSING_TOUCHINGCOLOR: "碰到顏色 %1 ?",
    SENSING_COLORISTOUCHINGCOLOR: "顏色 %1 碰到 %2 ?",
    SENSING_DISTANCETO: "到 %1 的距離",
    SENSING_DISTANCETO_POINTER: "滑鼠指標",
    SENSING_ASKANDWAIT: "詢問 %1 並等待",
    SENSING_ASK_TEXT: "你叫什麼名字？",
    SENSING_ANSWER: "回答",
    SENSING_KEYPRESSED: "按下 %1 鍵?",
    SENSING_MOUSEDOWN: "按下滑鼠?",
    SENSING_MOUSEX: "滑鼠的x座標",
    SENSING_MOUSEY: "滑鼠的y座標",
    SENSING_SETDRAGMODE: "將拖曳模式設為 %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "可拖曳",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖曳",
    SENSING_LOUDNESS: "響度",
    SENSING_LOUD: "響聲？",
    SENSING_TIMER: "計時器",
    SENSING_RESETTIMER: "計時器歸零",
    SENSING_OF: "%2 的 %1",
    SENSING_OF_XPOSITION: "x 座標",
    SENSING_OF_YPOSITION: "y 座標",
    SENSING_OF_DIRECTION: "方向",
    SENSING_OF_COSTUMENUMBER: "造型編號",
    SENSING_OF_COSTUMENAME: "造型名稱",
    SENSING_OF_SIZE: "大小",
    SENSING_OF_VOLUME: "音量",
    SENSING_OF_BACKDROPNUMBER: "背景編號",
    SENSING_OF_BACKDROPNAME: "背景名稱",
    SENSING_OF_STAGE: "舞台",
    SENSING_CURRENT: "目前時間的 %1",
    SENSING_CURRENT_YEAR: "年",
    SENSING_CURRENT_MONTH: "月",
    SENSING_CURRENT_DATE: "日",
    SENSING_CURRENT_DAYOFWEEK: "星期",
    SENSING_CURRENT_HOUR: "時",
    SENSING_CURRENT_MINUTE: "分",
    SENSING_CURRENT_SECOND: "秒",
    SENSING_DAYSSINCE2000: "2000年至今的天數",
    SENSING_USERNAME: "使用者名稱",
    SENSING_USERID: "用戶id",
    SOUND_PLAY: "播放聲音 %1",
    SOUND_PLAYUNTILDONE: "播放聲音 %1 等待播完",
    SOUND_STOPALLSOUNDS: "停止所有聲音",
    SOUND_SETEFFECTO: "將 %1 音效設為 %2",
    SOUND_CHANGEEFFECTBY: "增加 %1 音效 %2",
    SOUND_CLEAREFFECTS: "清除音效",
    SOUND_EFFECTS_PITCH: "音調",
    SOUND_EFFECTS_PAN: "左右平衡",
    SOUND_CHANGEVOLUMEBY: "音量增加 %1",
    SOUND_SETVOLUMETO: "將音量設為 %1%",
    SOUND_VOLUME: "音量",
    SOUND_RECORD: "錄音…",
    CATEGORY_MOTION: "運動",
    CATEGORY_MOVEMENT: "移動",
    CATEGORY_LOOKS: "外觀",
    CATEGORY_SOUND: "聲音",
    CATEGORY_EVENTS: "事件",
    CATEGORY_CONTROL: "控制",
    CATEGORY_SENSING: "偵測",
    CATEGORY_OPERATORS: "運算",
    CATEGORY_VARIABLES: "變數",
    CATEGORY_MYBLOCKS: "自製積木",
    DUPLICATE: "複製",
    DELETE: "刪除",
    ADD_COMMENT: "新增註解",
    REMOVE_COMMENT: "刪除註解",
    DELETE_BLOCK: "刪除",
    DELETE_X_BLOCKS: "刪除 %1 積木",
    DELETE_ALL_BLOCKS: "刪除全部 %1 積木？",
    CLEAN_UP: "整理積木",
    HELP: "幫助",
    UNDO: "撤銷",
    REDO: "重做",
    EDIT_PROCEDURE: "編輯",
    SHOW_PROCEDURE_DEFINITION: "查看定義",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "說些什麼…",
    COLOUR_HUE_LABEL: "顏色",
    COLOUR_SATURATION_LABEL: "飽和度",
    COLOUR_BRIGHTNESS_LABEL: "亮度",
    CHANGE_VALUE_TITLE: "更改變數：",
    RENAME_VARIABLE: "修改變數名",
    RENAME_VARIABLE_TITLE: "將所有的「%1」變數名稱改為：",
    RENAME_VARIABLE_MODAL_TITLE: "修改變數名稱",
    NEW_VARIABLE: "建立一個變數",
    NEW_VARIABLE_TITLE: "新變數名：",
    VARIABLE_MODAL_TITLE: "新變數",
    VARIABLE_ALREADY_EXISTS: "已經存在名為「%1」的變數。 ",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "已經存在一個名為「%1」的變量，其類型為「%2」。 ",
    DELETE_VARIABLE_CONFIRMATION: "刪除%1處「%2」變數嗎？ ",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "無法刪除變數「%1」，因為函數「%2」的定義中用到了它",
    DELETE_VARIABLE: "刪除變數“%1”",
    NEW_PROCEDURE: "製作新的積木",
    PROCEDURE_ALREADY_EXISTS: "已經存在名為「%1」的程式。 ",
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "在刪除一個積木定義前，請先把該積木從所有使用的地方刪除。",
    NEW_LIST: "建立一個清單",
    NEW_LIST_TITLE: "新的清單名稱：",
    LIST_MODAL_TITLE: "新清單",
    LIST_ALREADY_EXISTS: "名為 “%1” 的清單已存在。 ",
    RENAME_LIST_TITLE: "將所有的「%1」清單改名為：",
    RENAME_LIST_MODAL_TITLE: "修改清單名稱",
    DEFAULT_LIST_ITEM: "東西",
    DELETE_LIST: "刪除「%1」清單",
    RENAME_LIST: "修改清單名稱",
    NEW_BROADCAST_MESSAGE: "新訊息",
    NEW_BROADCAST_MESSAGE_TITLE: "新訊息的名稱：",
    BROADCAST_MODAL_TITLE: "新訊息",
    DEFAULT_BROADCAST_MESSAGE_NAME: "訊息1",
    // 聲音類別
    NXT_BUZZER_TONE: "播放警笛聲 %1 Hz 持續 %2 秒",
    NXT_BUZZER_NOTE: "播放音符 %1 持續 %2 秒",
    NXT_BUZZER_STOP: "停止所有聲音",
    
    // 顯示類別
    NXT_DISP_PRINTCOL: "在第 %2 列第 %3 行顯示 %1",
    NXT_DISP_CLEAR: "清除顯示",
    
    // 馬達類別
    NXT_MOTOR_RUNFOR: "%1 運轉 %2 %3 速度 %4%",
    NXT_MOTOR_ON: "%1 啟動馬達速度 %2%",
    NXT_MOTOR_OFF: "%1 停止馬達",
    NXT_MOTOR_RESET: "%1 重置轉動角度",
    NXT_MOTOR_DEGREES: "%1 轉動角度",
    
    // 移動類別
    NXT_MOVE_SETTING: "設定移動馬達為 %1 和 %2",
    NXT_MOVE_RUNFOR: " 以 %3 %4% 的速度移動 %1 %2 ",
    NXT_MOVE_ON: "以 %1 %2% 的速度開始移動",
    NXT_MOVE_OFF: "停止移動",
    
    // 感測器類別
    NXT_SENSORS_LIGHT_RFL: "%1 反射光強度",
    NXT_SENSORS_LIGHT_AMB: "%1 環境光強度",
    NXT_SENSORS_US: "%1 距離(公分)",
    NXT_SENSORS_SOUND: "%1 聲音等級",
    NXT_SENSORS_TOUCH: "%1 是否被按下？",
    NXT_SENSORS_BUTTON: "%1 按鈕是否被按下？",
    NXT_SENSORS_TIMER: "計時器(秒)",
    NXT_SENSORS_TIMER_RESET: "重置計時器",
    
    // 下拉選單選項
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",
    
    NXT_UNIT_ROTATIONS: "圈",
    NXT_UNIT_DEGREES: "度",
    NXT_UNIT_SECONDS: "秒",
    
    NXT_BUTTON_LEFT: "左",
    NXT_BUTTON_CENTER: "中",
    NXT_BUTTON_RIGHT: "右"
};
