"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
    CONTROL_SETUP: "when program starts",
    CONTROL_FOREVER: "forever",
    CONTROL_REPEAT: "repeat %1",
    CONTROL_IF: "if %1 then",
    CONTROL_ELSE: "else",
    CONTROL_STOP: "stop",
    CONTROL_STOP_ALL: "all",
    CONTROL_STOP_THIS: "this script",
    CONTROL_STOP_OTHER: "other scripts in sprite",
    CONTROL_WAIT: "wait %1 seconds",
    CONTROL_WAITUNTIL: "wait until %1",
    CONTROL_REPEATUNTIL: "repeat until %1",
    CONTROL_WHILE: "while %1",
    CONTROL_FOREACH: "for each %1 in %2",
    CONTROL_STARTASCLONE: "when I start as a clone",
    CONTROL_CREATECLONEOF: "create clone of %1",
    CONTROL_CREATECLONEOF_MYSELF: "myself",
    CONTROL_DELETETHISCLONE: "delete this clone",
    CONTROL_COUNTER: "counter",
    CONTROL_INCRCOUNTER: "increment counter",
    CONTROL_CLEARCOUNTER: "clear counter",
    CONTROL_ALLATONCE: "all at once",
    DATA_SETVARIABLETO: "set %1 to %2",
    DATA_CHANGEVARIABLEBY: "change %1 by %2",
    DATA_SHOWVARIABLE: "show variable %1",
    DATA_HIDEVARIABLE: "hide variable %1",
    DATA_ADDTOLIST: "add %1 to %2",
    DATA_DELETEOFLIST: "delete %1 of %2",
    DATA_DELETEALLOFLIST: "delete all of %1",
    DATA_INSERTATLIST: "insert %1 at %2 of %3",
    DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
    DATA_ITEMOFLIST: "item %1 of %2",
    DATA_ITEMNUMOFLIST: "item # of %1 in %2",
    DATA_LENGTHOFLIST: "length of %1",
    DATA_LISTCONTAINSITEM: "%1 contains %2?",
    DATA_SHOWLIST: "show list %1",
    DATA_HIDELIST: "hide list %1",
    DATA_INDEX_ALL: "all",
    DATA_INDEX_LAST: "last",
    DATA_INDEX_RANDOM: "random",
    EVENT_WHENFLAGCLICKED: "when %1 clicked",
    EVENT_WHENTHISSPRITECLICKED: "when this sprite clicked",
    EVENT_WHENSTAGECLICKED: "when stage clicked",
    EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
    EVENT_WHENBROADCASTRECEIVED: "when I receive %1",
    EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
    EVENT_WHENGREATERTHAN: "when %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "timer",
    EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
    EVENT_BROADCAST: "broadcast %1",
    EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
    EVENT_WHENKEYPRESSED: "when %1 key pressed",
    EVENT_WHENKEYPRESSED_SPACE: "space",
    EVENT_WHENKEYPRESSED_LEFT: "left arrow",
    EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
    EVENT_WHENKEYPRESSED_DOWN: "down arrow",
    EVENT_WHENKEYPRESSED_UP: "up arrow",
    EVENT_WHENKEYPRESSED_ANY: "any",
    LOOKS_SAYFORSECS: "say %1 for %2 seconds",
    LOOKS_SAY: "say %1",
    LOOKS_HELLO: "Hello!",
    LOOKS_THINKFORSECS: "think %1 for %2 seconds",
    LOOKS_THINK: "think %1",
    LOOKS_HMM: "Hmm...",
    LOOKS_SHOW: "show",
    LOOKS_HIDE: "hide",
    LOOKS_HIDEALLSPRITES: "hide all sprites",
    LOOKS_EFFECT_COLOR: "color",
    LOOKS_EFFECT_FISHEYE: "fisheye",
    LOOKS_EFFECT_WHIRL: "whirl",
    LOOKS_EFFECT_PIXELATE: "pixelate",
    LOOKS_EFFECT_MOSAIC: "mosaic",
    LOOKS_EFFECT_BRIGHTNESS: "brightness",
    LOOKS_EFFECT_GHOST: "ghost",
    LOOKS_CHANGEEFFECTBY: "change %1 effect by %2",
    LOOKS_SETEFFECTTO: "set %1 effect to %2",
    LOOKS_CLEARGRAPHICEFFECTS: "clear graphic effects",
    LOOKS_CHANGESIZEBY: "change size by %1",
    LOOKS_SETSIZETO: "set size to %1 %",
    LOOKS_SIZE: "size",
    LOOKS_CHANGESTRETCHBY: "change stretch by %1",
    LOOKS_SETSTRETCHTO: "set stretch to %1 %",
    LOOKS_SWITCHCOSTUMETO: "switch costume to %1",
    LOOKS_NEXTCOSTUME: "next costume",
    LOOKS_SWITCHBACKDROPTO: "switch backdrop to %1",
    LOOKS_GOTOFRONTBACK: "go to %1 layer",
    LOOKS_GOTOFRONTBACK_FRONT: "front",
    LOOKS_GOTOFRONTBACK_BACK: "back",
    LOOKS_GOFORWARDBACKWARDLAYERS: "go %1 %2 layers",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "forward",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "backward",
    LOOKS_BACKDROPNUMBERNAME: "backdrop %1",
    LOOKS_COSTUMENUMBERNAME: "costume %1",
    LOOKS_NUMBERNAME_NUMBER: "number",
    LOOKS_NUMBERNAME_NAME: "name",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "switch backdrop to %1 and wait",
    LOOKS_NEXTBACKDROP_BLOCK: "next backdrop",
    LOOKS_NEXTBACKDROP: "next backdrop",
    LOOKS_PREVIOUSBACKDROP: "previous backdrop",
    LOOKS_RANDOMBACKDROP: "random backdrop",
    MOTION_MOVESTEPS: "move %1 steps",
    MOTION_TURNLEFT: "turn %1 %2 degrees",
    MOTION_TURNRIGHT: "turn %1 %2 degrees",
    MOTION_POINTINDIRECTION: "point in direction %1",
    MOTION_POINTTOWARDS: "point towards %1",
    MOTION_POINTTOWARDS_POINTER: "mouse-pointer",
    MOTION_POINTTOWARDS_RANDOM: "random direction",
    MOTION_GOTO: "go to %1",
    MOTION_GOTO_POINTER: "mouse-pointer",
    MOTION_GOTO_RANDOM: "random position",
    MOTION_GOTOXY: "go to x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "glide %1 secs to x: %2 y: %3",
    MOTION_GLIDETO: "glide %1 secs to %2",
    MOTION_GLIDETO_POINTER: "mouse-pointer",
    MOTION_GLIDETO_RANDOM: "random position",
    MOTION_CHANGEXBY: "change x by %1",
    MOTION_SETX: "set x to %1",
    MOTION_CHANGEYBY: "change y by %1",
    MOTION_SETY: "set y to %1",
    MOTION_IFONEDGEBOUNCE: "if on edge, bounce",
    MOTION_SETROTATIONSTYLE: "set rotation style %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "left-right",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "don't rotate",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "all around",
    MOTION_XPOSITION: "x position",
    MOTION_YPOSITION: "y position",
    MOTION_DIRECTION: "direction",
    MOTION_SCROLLRIGHT: "scroll right %1",
    MOTION_SCROLLUP: "scroll up %1",
    MOTION_ALIGNSCENE: "align scene %1",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "bottom-left",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "bottom-right",
    MOTION_ALIGNSCENE_MIDDLE: "middle",
    MOTION_ALIGNSCENE_TOPLEFT: "top-left",
    MOTION_ALIGNSCENE_TOPRIGHT: "top-right",
    MOTION_XSCROLL: "x scroll",
    MOTION_YSCROLL: "y scroll",
    MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "pick random %1 to %2",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 and %2",
    OPERATORS_OR: "%1 or %2",
    OPERATORS_NOT: "not %1",
    OPERATORS_JOIN: "join %1 and %2",
    OPERATORS_JOIN_THREE: "join %1 and %2 and %3",
    OPERATORS_CONSTRAINS: "Constrains %1 in Min:%2 Max:%3",
    OPERATORS_JOIN_APPLE: "apple",
    OPERATORS_JOIN_BANANA: "banana",
    OPERATORS_LETTEROF: "letter %1 of %2",
    OPERATORS_LETTEROF_APPLE: "a",
    OPERATORS_LENGTH: "length of %1",
    OPERATORS_CONTAINS: "%1 contains %2?",
    OPERATORS_MOD: "%1 mod %2",
    OPERATORS_ROUND: "round %1",
    OPERATORS_MATHOP: "%1 of %2",
    OPERATORS_MATHOP_ABS: "abs",
    OPERATORS_MATHOP_FLOOR: "floor",
    OPERATORS_MATHOP_CEILING: "ceiling",
    OPERATORS_MATHOP_SQRT: "sqrt",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
    OPERATORS_TOSTRING: "%1 to String",
    PROCEDURES_DEFINITION: "define %1",
    SENSING_TOUCHINGOBJECT: "touching %1?",
    SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
    SENSING_TOUCHINGOBJECT_EDGE: "edge",
    SENSING_TOUCHINGCOLOR: "touching color %1?",
    SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
    SENSING_DISTANCETO: "distance to %1",
    SENSING_DISTANCETO_POINTER: "mouse-pointer",
    SENSING_ASKANDWAIT: "ask %1 and wait",
    SENSING_ASK_TEXT: "What's your name?",
    SENSING_ANSWER: "answer",
    SENSING_KEYPRESSED: "key %1 pressed?",
    SENSING_MOUSEDOWN: "mouse down?",
    SENSING_MOUSEX: "mouse x",
    SENSING_MOUSEY: "mouse y",
    SENSING_SETDRAGMODE: "set drag mode %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
    SENSING_LOUDNESS: "loudness",
    SENSING_LOUD: "loud?",
    SENSING_TIMER: "timer",
    SENSING_RESETTIMER: "reset timer",
    SENSING_OF: "%1 of %2",
    SENSING_OF_XPOSITION: "x position",
    SENSING_OF_YPOSITION: "y position",
    SENSING_OF_DIRECTION: "direction",
    SENSING_OF_COSTUMENUMBER: "costume #",
    SENSING_OF_COSTUMENAME: "costume name",
    SENSING_OF_SIZE: "size",
    SENSING_OF_VOLUME: "volume",
    SENSING_OF_BACKDROPNUMBER: "backdrop #",
    SENSING_OF_BACKDROPNAME: "backdrop name",
    SENSING_OF_STAGE: "Stage",
    SENSING_CURRENT: "current %1",
    SENSING_CURRENT_YEAR: "year",
    SENSING_CURRENT_MONTH: "month",
    SENSING_CURRENT_DATE: "date",
    SENSING_CURRENT_DAYOFWEEK: "day of week",
    SENSING_CURRENT_HOUR: "hour",
    SENSING_CURRENT_MINUTE: "minute",
    SENSING_CURRENT_SECOND: "second",
    SENSING_DAYSSINCE2000: "days since 2000",
    SENSING_USERNAME: "username",
    SENSING_USERID: "user id",
    SOUND_PLAY: "start sound %1",
    SOUND_PLAYUNTILDONE: "play sound %1 until done",
    SOUND_STOPALLSOUNDS: "stop all sounds",
    SOUND_SETEFFECTO: "set %1 effect to %2",
    SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
    SOUND_CLEAREFFECTS: "clear sound effects",
    SOUND_EFFECTS_PITCH: "pitch",
    SOUND_EFFECTS_PAN: "pan left/right",
    SOUND_CHANGEVOLUMEBY: "change volume by %1",
    SOUND_SETVOLUMETO: "set volume to %1%",
    SOUND_VOLUME: "volume",
    SOUND_RECORD: "record...",
    CATEGORY_MOTION: "Motor",
    CATEGORY_MOVEMENT: "Movement",
    CATEGORY_LOOKS: "Display",
    CATEGORY_SOUND: "Sound",
    CATEGORY_EVENTS: "Events",
    CATEGORY_CONTROL: "Control",
    CATEGORY_SENSING: "Sensors",
    CATEGORY_OPERATORS: "Operators",
    CATEGORY_VARIABLES: "Variables",
    CATEGORY_MYBLOCKS: "My Blocks",
    DUPLICATE: "Duplicate",
    DELETE: "Delete",
    ADD_COMMENT: "Add Comment",
    REMOVE_COMMENT: "Remove Comment",
    DELETE_BLOCK: "Delete Block",
    DELETE_X_BLOCKS: "Delete %1 Blocks",
    DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
    CLEAN_UP: "Clean up Blocks",
    HELP: "Help",
    UNDO: "Undo",
    REDO: "Redo",
    EDIT_PROCEDURE: "Edit",
    SHOW_PROCEDURE_DEFINITION: "Go to definition",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
    COLOUR_HUE_LABEL: "Color",
    COLOUR_SATURATION_LABEL: "Saturation",
    COLOUR_BRIGHTNESS_LABEL: "Brightness",
    CHANGE_VALUE_TITLE: "Change value:",
    RENAME_VARIABLE: "Rename variable",
    RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
    RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
    NEW_VARIABLE: "Make a Variable",
    NEW_VARIABLE_TITLE: "New variable name:",
    VARIABLE_MODAL_TITLE: "New Variable",
    VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: 'A variable named "%1" already exists for another variable of type "%2".',
    DELETE_VARIABLE_CONFIRMATION: 'Delete %1 uses of the "%2" variable?',
    CANNOT_DELETE_VARIABLE_PROCEDURE: 'Can\'t delete the variable "%1" because it\'s part of the definition of the function "%2"',
    DELETE_VARIABLE: 'Delete the "%1" variable',
    NEW_PROCEDURE: "Make a Block",
    PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "To delete a block definition, first remove all uses of the block",
    NEW_LIST: "Make a List",
    NEW_LIST_TITLE: "New list name:",
    LIST_MODAL_TITLE: "New List",
    LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
    RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
    RENAME_LIST_MODAL_TITLE: "Rename List",
    DEFAULT_LIST_ITEM: "thing",
    DELETE_LIST: 'Delete the "%1" list',
    RENAME_LIST: "Rename list",
    NEW_BROADCAST_MESSAGE: "New message",
    NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
    BROADCAST_MODAL_TITLE: "New Message",
    DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
    // Sound category
    NXT_BUZZER_TONE: "Play beep %1 Hz for %2 seconds",
    NXT_BUZZER_NOTE: "Play note %1 for %2 seconds",
    NXT_BUZZER_STOP: "Stop all sounds",
    
    // Display category
    NXT_DISP_PRINTCOL: "Write %1 at Col%2 Line%3",
    NXT_DISP_CLEAR: "Clear display",
    
    // Motor category
    NXT_MOTOR_RUNFOR: "%1 run for %2 %3 at %4% speed",
    NXT_MOTOR_ON: "%1 start motor at %2% speed",
    NXT_MOTOR_OFF: "%1 stop motor",
    NXT_MOTOR_RESET: "%1 reset degrees counted",
    NXT_MOTOR_DEGREES: "%1 degrees counted",
    
    // Movement category
    NXT_MOVE_SETTING: "Set movement motor to %1 and %2",
    NXT_MOVE_RUNFOR: "Move for %1 %2 at %3% %4% speed",
    NXT_MOVE_ON: "Start moving at %1% %2% speed",
    NXT_MOVE_OFF: "Stop moving",
    
    // Sensor category
    NXT_SENSORS_LIGHT_RFL: "%1 reflected light intensity",
    NXT_SENSORS_LIGHT_AMB: "%1 ambient light intensity",
    NXT_SENSORS_US: "%1 distance in cm",
    NXT_SENSORS_SOUND: "%1 sound level",
    NXT_SENSORS_TOUCH: "%1 is pressed?",
    NXT_SENSORS_BUTTON: "is %1 button pressed?",
    NXT_SENSORS_TIMER: "Timer (secs)",
    NXT_SENSORS_TIMER_RESET: "Reset timer",
    
    // Dropdown options
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",
    
    NXT_UNIT_ROTATIONS: "rotations",
    NXT_UNIT_DEGREES: "degrees",
    NXT_UNIT_SECONDS: "seconds",
    
    NXT_BUTTON_LEFT: "Left",
    NXT_BUTTON_CENTER: "Center",
    NXT_BUTTON_RIGHT: "Right"
};

Blockly.ScratchMsgs.locales["zh-tw"] = {
    CONTROL_SETUP: "當程式開始時",
    CONTROL_FOREVER: "重複執行",
    CONTROL_REPEAT: "重複執行 %1 次",
    CONTROL_IF: "如果 %1 那麼",
    CONTROL_ELSE: "否則",
    CONTROL_STOP: "停止",
    CONTROL_STOP_ALL: "全部腳本",
    CONTROL_STOP_THIS: "這個腳本",
    CONTROL_STOP_OTHER: "該角色的其他腳本",
    CONTROL_WAIT: "等待 %1 秒",
    CONTROL_WAITUNTIL: "等待 %1",
    CONTROL_REPEATUNTIL: "重複執行直到 %1",
    CONTROL_WHILE: "當 %1 重複執行",
    CONTROL_FOREACH: "對於 %2 中的每個 %1",
    CONTROL_STARTASCLONE: "當作為克隆體啟動時",
    CONTROL_CREATECLONEOF: "克隆 %1",
    CONTROL_CREATECLONEOF_MYSELF: "自己",
    CONTROL_DELETETHISCLONE: "刪除此複製體",
    CONTROL_COUNTER: "計數器",
    CONTROL_INCRCOUNTER: "計數器加一",
    CONTROL_CLEARCOUNTER: "計數器歸零",
    CONTROL_ALLATONCE: "所有腳本",
    DATA_SETVARIABLETO: "將 %1 設為 %2",
    DATA_CHANGEVARIABLEBY: "增加 %1 %2",
    DATA_SHOWVARIABLE: "顯示變數 %1",
    DATA_HIDEVARIABLE: "隱藏變數 %1",
    DATA_ADDTOLIST: "將 %1 加入 %2",
    DATA_DELETEOFLIST: "刪除 %2 的第 %1 項",
    DATA_DELETEALLOFLIST: "刪除 %1 的全部項目",
    DATA_INSERTATLIST: "在 %3 的第 %2 項前插入 %1",
    DATA_REPLACEITEMOFLIST: "將 %2 的第 %1 項替換為 %3",
    DATA_ITEMOFLIST: "%2 的第 %1 項",
    DATA_ITEMNUMOFLIST: "%2 中第一個 %1 的編號",
    DATA_LENGTHOFLIST: "%1 的項目數",
    DATA_LISTCONTAINSITEM: "%1 包含 %2 ?",
    DATA_SHOWLIST: "顯示清單 %1",
    DATA_HIDELIST: "隱藏清單 %1",
    DATA_INDEX_ALL: "全部",
    DATA_INDEX_LAST: "結尾",
    DATA_INDEX_RANDOM: "隨機",
    EVENT_WHENFLAGCLICKED: "當 %1 被點擊",
    EVENT_WHENTHISSPRITECLICKED: "當角色被點擊",
    EVENT_WHENSTAGECLICKED: "當舞台點擊",
    EVENT_WHENTOUCHINGOBJECT: "當角色碰到 %1",
    EVENT_WHENBROADCASTRECEIVED: "當接收到 %1",
    EVENT_WHENBACKDROPSWITCHESTO: "當背景換成 %1",
    EVENT_WHENGREATERTHAN: "當 %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "計時器",
    EVENT_WHENGREATERTHAN_LOUDNESS: "響度",
    EVENT_BROADCAST: "廣播 %1",
    EVENT_BROADCASTANDWAIT: "廣播 %1 並等待",
    EVENT_WHENKEYPRESSED: "當按下 %1 鍵",
    EVENT_WHENKEYPRESSED_SPACE: "空格",
    EVENT_WHENKEYPRESSED_LEFT: "←",
    EVENT_WHENKEYPRESSED_RIGHT: "→",
    EVENT_WHENKEYPRESSED_DOWN: "↓",
    EVENT_WHENKEYPRESSED_UP: "↑",
    EVENT_WHENKEYPRESSED_ANY: "任意",
    LOOKS_SAYFORSECS: "說 %1 %2 秒",
    LOOKS_SAY: "說 %1",
    LOOKS_HELLO: "你好！",
    LOOKS_THINKFORSECS: "思考 %1 %2 秒",
    LOOKS_THINK: "思考 %1",
    LOOKS_HMM: "嗯…",
    LOOKS_SHOW: "顯示",
    LOOKS_HIDE: "隱藏",
    LOOKS_HIDEALLSPRITES: "隱藏所有角色",
    LOOKS_EFFECT_COLOR: "顏色",
    LOOKS_EFFECT_FISHEYE: "魚眼",
    LOOKS_EFFECT_WHIRL: "漩渦",
    LOOKS_EFFECT_PIXELATE: "像素化",
    LOOKS_EFFECT_MOSAIC: "馬賽克",
    LOOKS_EFFECT_BRIGHTNESS: "亮度",
    LOOKS_EFFECT_GHOST: "虛像",
    LOOKS_CHANGEEFFECTBY: "將 %1 特效增加 %2",
    LOOKS_SETEFFECTTO: "將 %1 特效設定為 %2",
    LOOKS_CLEARGRAPHICEFFECTS: "清除圖形特效",
    LOOKS_CHANGESIZEBY: "將大小增加 %1",
    LOOKS_SETSIZETO: "將大小設為 %1",
    LOOKS_SIZE: "大小",
    LOOKS_CHANGESTRETCHBY: "伸縮%1",
    LOOKS_SETSTRETCHTO: "設定伸縮為%1 %",
    LOOKS_SWITCHCOSTUMETO: "換成 %1 造型",
    LOOKS_NEXTCOSTUME: "下一個造型",
    LOOKS_SWITCHBACKDROPTO: "換成 %1 背景",
    LOOKS_GOTOFRONTBACK: "移到最 %1 ",
    LOOKS_GOTOFRONTBACK_FRONT: "前面",
    LOOKS_GOTOFRONTBACK_BACK: "後面",
    LOOKS_GOFORWARDBACKWARDLAYERS: "%1 %2 層",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "前移",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "後移",
    LOOKS_BACKDROPNUMBERNAME: "背景 %1",
    LOOKS_COSTUMENUMBERNAME: "造型 %1",
    LOOKS_NUMBERNAME_NUMBER: "編號",
    LOOKS_NUMBERNAME_NAME: "名稱",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "換成 %1 背景並等待",
    LOOKS_NEXTBACKDROP_BLOCK: "下一個背景",
    LOOKS_NEXTBACKDROP: "下一個背景",
    LOOKS_PREVIOUSBACKDROP: "上一個背景",
    LOOKS_RANDOMBACKDROP: "隨機背景",
    MOTION_MOVESTEPS: "移動 %1 步驟",
    MOTION_TURNLEFT: "左轉 %1 %2 度",
    MOTION_TURNRIGHT: "右轉 %1 %2 度",
    MOTION_POINTINDIRECTION: "面向 %1 方向",
    MOTION_POINTTOWARDS: "面向 %1",
    MOTION_POINTTOWARDS_POINTER: "滑鼠指標",
    MOTION_POINTTOWARDS_RANDOM: "隨機方向",
    MOTION_GOTO: "移到 %1",
    MOTION_GOTO_POINTER: "滑鼠指標",
    MOTION_GOTO_RANDOM: "隨機位置",
    MOTION_GOTOXY: "移到 x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "在 %1 秒內滑到 x: %2 y: %3",
    MOTION_GLIDETO: "在 %1 秒內滑到 %2",
    MOTION_GLIDETO_POINTER: "滑鼠指標",
    MOTION_GLIDETO_RANDOM: "隨機位置",
    MOTION_CHANGEXBY: "將x座標增加 %1",
    MOTION_SETX: "將x座標設為 %1",
    MOTION_CHANGEYBY: "將y座標增加 %1",
    MOTION_SETY: "將y座標設為 %1",
    MOTION_IFONEDGEBOUNCE: "碰到邊緣就反彈",
    MOTION_SETROTATIONSTYLE: "將旋轉方式設為 %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "左右翻轉",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "不可旋轉",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "任意旋轉",
    MOTION_XPOSITION: "x 座標",
    MOTION_YPOSITION: "y 座標",
    MOTION_DIRECTION: "方向",
    MOTION_SCROLLRIGHT: "向右捲動 %1",
    MOTION_SCROLLUP: "向上捲動 %1",
    MOTION_ALIGNSCENE: "與場景 %1 對齊",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "左下角",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "右下角",
    MOTION_ALIGNSCENE_MIDDLE: "中間",
    MOTION_ALIGNSCENE_TOPLEFT: "左上角",
    MOTION_ALIGNSCENE_TOPRIGHT: "右上角",
    MOTION_XSCROLL: "x滾動位置",
    MOTION_YSCROLL: "y滾動位置",
    MOTION_STAGE_SELECTED: "選中了舞台：不可使用運動類積木",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "在 %1 和 %2 之間取隨機數",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 且 %2",
    OPERATORS_OR: "%1 或 %2",
    OPERATORS_NOT: "%1 不成立",
    OPERATORS_JOIN: "連接 %1 和 %2",
    OPERATORS_JOIN_THREE: "連接 %1 和 %2 和 %3",
    OPERATORS_CONSTRAINS: "限制%1在最小:%2 最大:%3之間",
    OPERATORS_JOIN_APPLE: "蘋果",
    OPERATORS_JOIN_BANANA: "香蕉",
    OPERATORS_LETTEROF: "%2 的第 %1 個字元",
    OPERATORS_LETTEROF_APPLE: "果實",
    OPERATORS_LENGTH: "%1 的字元數",
    OPERATORS_CONTAINS: "%1 包含 %2 ?",
    OPERATORS_MOD: "%1 除以 %2 的餘數",
    OPERATORS_ROUND: "四捨五入 %1",
    OPERATORS_MATHOP: "%1 %2",
    OPERATORS_MATHOP_ABS: "絕對值",
    OPERATORS_MATHOP_FLOOR: "向下取整",
    OPERATORS_MATHOP_CEILING: "向上取整",
    OPERATORS_MATHOP_SQRT: "平方根",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e ^",
    OPERATORS_MATHOP_10EXP: "10 ^",
    OPERATORS_TOSTRING: "%1 轉為字串",
    PROCEDURES_DEFINITION: "定義 %1",
    SENSING_TOUCHINGOBJECT: "碰到 %1 ?",
    SENSING_TOUCHINGOBJECT_POINTER: "滑鼠指標",
    SENSING_TOUCHINGOBJECT_EDGE: "舞台邊緣",
    SENSING_TOUCHINGCOLOR: "碰到顏色 %1 ?",
    SENSING_COLORISTOUCHINGCOLOR: "顏色 %1 碰到 %2 ?",
    SENSING_DISTANCETO: "到 %1 的距離",
    SENSING_DISTANCETO_POINTER: "滑鼠指標",
    SENSING_ASKANDWAIT: "詢問 %1 並等待",
    SENSING_ASK_TEXT: "你叫什麼名字？",
    SENSING_ANSWER: "回答",
    SENSING_KEYPRESSED: "按下 %1 鍵?",
    SENSING_MOUSEDOWN: "按下滑鼠?",
    SENSING_MOUSEX: "滑鼠的x座標",
    SENSING_MOUSEY: "滑鼠的y座標",
    SENSING_SETDRAGMODE: "將拖曳模式設為 %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "可拖曳",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖曳",
    SENSING_LOUDNESS: "響度",
    SENSING_LOUD: "響聲？",
    SENSING_TIMER: "計時器",
    SENSING_RESETTIMER: "計時器歸零",
    SENSING_OF: "%2 的 %1",
    SENSING_OF_XPOSITION: "x 座標",
    SENSING_OF_YPOSITION: "y 座標",
    SENSING_OF_DIRECTION: "方向",
    SENSING_OF_COSTUMENUMBER: "造型編號",
    SENSING_OF_COSTUMENAME: "造型名稱",
    SENSING_OF_SIZE: "大小",
    SENSING_OF_VOLUME: "音量",
    SENSING_OF_BACKDROPNUMBER: "背景編號",
    SENSING_OF_BACKDROPNAME: "背景名稱",
    SENSING_OF_STAGE: "舞台",
    SENSING_CURRENT: "目前時間的 %1",
    SENSING_CURRENT_YEAR: "年",
    SENSING_CURRENT_MONTH: "月",
    SENSING_CURRENT_DATE: "日",
    SENSING_CURRENT_DAYOFWEEK: "星期",
    SENSING_CURRENT_HOUR: "時",
    SENSING_CURRENT_MINUTE: "分",
    SENSING_CURRENT_SECOND: "秒",
    SENSING_DAYSSINCE2000: "2000年至今的天數",
    SENSING_USERNAME: "使用者名稱",
    SENSING_USERID: "用戶id",
    SOUND_PLAY: "播放聲音 %1",
    SOUND_PLAYUNTILDONE: "播放聲音 %1 等待播完",
    SOUND_STOPALLSOUNDS: "停止所有聲音",
    SOUND_SETEFFECTO: "將 %1 音效設為 %2",
    SOUND_CHANGEEFFECTBY: "增加 %1 音效 %2",
    SOUND_CLEAREFFECTS: "清除音效",
    SOUND_EFFECTS_PITCH: "音調",
    SOUND_EFFECTS_PAN: "左右平衡",
    SOUND_CHANGEVOLUMEBY: "音量增加 %1",
    SOUND_SETVOLUMETO: "將音量設為 %1%",
    SOUND_VOLUME: "音量",
    SOUND_RECORD: "錄音…",
    CATEGORY_MOTION: "運動",
    CATEGORY_MOVEMENT: "移動",
    CATEGORY_LOOKS: "外觀",
    CATEGORY_SOUND: "聲音",
    CATEGORY_EVENTS: "事件",
    CATEGORY_CONTROL: "控制",
    CATEGORY_SENSING: "偵測",
    CATEGORY_OPERATORS: "運算",
    CATEGORY_VARIABLES: "變數",
    CATEGORY_MYBLOCKS: "自製積木",
    DUPLICATE: "複製",
    DELETE: "刪除",
    ADD_COMMENT: "新增註解",
    REMOVE_COMMENT: "刪除註解",
    DELETE_BLOCK: "刪除",
    DELETE_X_BLOCKS: "刪除 %1 積木",
    DELETE_ALL_BLOCKS: "刪除全部 %1 積木？",
    CLEAN_UP: "整理積木",
    HELP: "幫助",
    UNDO: "撤銷",
    REDO: "重做",
    EDIT_PROCEDURE: "編輯",
    SHOW_PROCEDURE_DEFINITION: "查看定義",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "說些什麼…",
    COLOUR_HUE_LABEL: "顏色",
    COLOUR_SATURATION_LABEL: "飽和度",
    COLOUR_BRIGHTNESS_LABEL: "亮度",
    CHANGE_VALUE_TITLE: "更改變數：",
    RENAME_VARIABLE: "修改變數名",
    RENAME_VARIABLE_TITLE: "將所有的「%1」變數名稱改為：",
    RENAME_VARIABLE_MODAL_TITLE: "修改變數名稱",
    NEW_VARIABLE: "建立一個變數",
    NEW_VARIABLE_TITLE: "新變數名：",
    VARIABLE_MODAL_TITLE: "新變數",
    VARIABLE_ALREADY_EXISTS: "已經存在名為「%1」的變數。 ",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "已經存在一個名為「%1」的變量，其類型為「%2」。 ",
    DELETE_VARIABLE_CONFIRMATION: "刪除%1處「%2」變數嗎？ ",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "無法刪除變數「%1」，因為函數「%2」的定義中用到了它",
    DELETE_VARIABLE: "刪除變數“%1”",
    NEW_PROCEDURE: "製作新的積木",
    PROCEDURE_ALREADY_EXISTS: "已經存在名為「%1」的程式。 ",
    PROCEDURE_DEFAULT_NAME: "MyBlock",
    PROCEDURE_USED: "在刪除一個積木定義前，請先把該積木從所有使用的地方刪除。",
    NEW_LIST: "建立一個清單",
    NEW_LIST_TITLE: "新的清單名稱：",
    LIST_MODAL_TITLE: "新清單",
    LIST_ALREADY_EXISTS: "名為 “%1” 的清單已存在。 ",
    RENAME_LIST_TITLE: "將所有的「%1」清單改名為：",
    RENAME_LIST_MODAL_TITLE: "修改清單名稱",
    DEFAULT_LIST_ITEM: "東西",
    DELETE_LIST: "刪除「%1」清單",
    RENAME_LIST: "修改清單名稱",
    NEW_BROADCAST_MESSAGE: "新訊息",
    NEW_BROADCAST_MESSAGE_TITLE: "新訊息的名稱：",
    BROADCAST_MODAL_TITLE: "新訊息",
    DEFAULT_BROADCAST_MESSAGE_NAME: "訊息1",
    // 聲音類別
    NXT_BUZZER_TONE: "播放警笛聲 %1 Hz 持續 %2 秒",
    NXT_BUZZER_NOTE: "播放音符 %1 持續 %2 秒",
    NXT_BUZZER_STOP: "停止所有聲音",
    
    // 顯示類別
    NXT_DISP_PRINTCOL: "在第 %2 列第 %3 行顯示 %1",
    NXT_DISP_CLEAR: "清除顯示",
    
    // 馬達類別
    NXT_MOTOR_RUNFOR: "%1 運轉 %2 %3 速度 %4%",
    NXT_MOTOR_ON: "%1 啟動馬達速度 %2%",
    NXT_MOTOR_OFF: "%1 停止馬達",
    NXT_MOTOR_RESET: "%1 重置轉動角度",
    NXT_MOTOR_DEGREES: "%1 轉動角度",
    
    // 移動類別
    NXT_MOVE_SETTING: "設定移動馬達為 %1 和 %2",
    NXT_MOVE_RUNFOR: " 以 %3 %4% 的速度移動 %1 %2 ",
    NXT_MOVE_ON: "以 %1 %2% 的速度開始移動",
    NXT_MOVE_OFF: "停止移動",
    
    // 感測器類別
    NXT_SENSORS_LIGHT_RFL: "%1 反射光強度",
    NXT_SENSORS_LIGHT_AMB: "%1 環境光強度",
    NXT_SENSORS_US: "%1 距離(公分)",
    NXT_SENSORS_SOUND: "%1 聲音等級",
    NXT_SENSORS_TOUCH: "%1 是否被按下？",
    NXT_SENSORS_BUTTON: "%1 按鈕是否被按下？",
    NXT_SENSORS_TIMER: "計時器(秒)",
    NXT_SENSORS_TIMER_RESET: "重置計時器",
    
    // 下拉選單選項
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",
    
    NXT_UNIT_ROTATIONS: "圈",
    NXT_UNIT_DEGREES: "度",
    NXT_UNIT_SECONDS: "秒",
    
    NXT_BUTTON_LEFT: "左",
    NXT_BUTTON_CENTER: "中",
    NXT_BUTTON_RIGHT: "右"
};

// German and French standard Scratch messages are adapted from
// Scratch Blocks (Scratch Foundation), commit 601be05661de5665cb388ff17e50c76a675eb92e:
// https://github.com/scratchfoundation/scratch-blocks/blob/601be05661de5665cb388ff17e50c76a675eb92e/msg/scratch_msgs.js
// Apache License 2.0; see licenses/scratch-blocks.txt.
// Modified for NXT categories, custom blocks and terminology; reviewed wording
// and retained all input placeholders. Pitch names use international notation.

Blockly.ScratchMsgs.locales["de"] = {
    CONTROL_SETUP: "Wenn das Programm startet",
    CONTROL_FOREVER: "wiederhole fortlaufend",
    CONTROL_REPEAT: "wiederhole %1 mal",
    CONTROL_IF: "falls %1, dann",
    CONTROL_ELSE: "sonst",
    CONTROL_STOP: "stoppe",
    CONTROL_STOP_ALL: "alles",
    CONTROL_STOP_THIS: "dieses Skript",
    CONTROL_STOP_OTHER: "andere Skripte der Figur",
    CONTROL_WAIT: "warte %1 Sekunden",
    CONTROL_WAITUNTIL: "warte bis %1",
    CONTROL_REPEATUNTIL: "wiederhole bis %1",
    CONTROL_WHILE: "wiederhole solange %1",
    CONTROL_FOREACH: "wiederhole für jedes %1 in %2",
    CONTROL_STARTASCLONE: "Wenn ich als Klon entstehe",
    CONTROL_CREATECLONEOF: "erzeuge Klon von %1",
    CONTROL_CREATECLONEOF_MYSELF: "mir selbst",
    CONTROL_DELETETHISCLONE: "lösche diesen Klon",
    CONTROL_COUNTER: "Zähler",
    CONTROL_INCRCOUNTER: "erhöhe Zähler",
    CONTROL_CLEARCOUNTER: "setze Zähler zurück",
    CONTROL_ALLATONCE: "Alle gleichzeitig",
    DATA_SETVARIABLETO: "setze %1 auf %2",
    DATA_CHANGEVARIABLEBY: "ändere %1 um %2",
    DATA_SHOWVARIABLE: "zeige Variable %1",
    DATA_HIDEVARIABLE: "verstecke Variable %1",
    DATA_ADDTOLIST: "füge %1 zu %2 hinzu",
    DATA_DELETEOFLIST: "lösche %1 aus %2",
    DATA_DELETEALLOFLIST: "lösche alles aus %1",
    DATA_INSERTATLIST: "füge %1 bei %2 in %3 ein",
    DATA_REPLACEITEMOFLIST: "ersetze Element %1 von %2 durch %3",
    DATA_ITEMOFLIST: "Element %1 von %2",
    DATA_ITEMNUMOFLIST: "Nummer von %1 in %2",
    DATA_LENGTHOFLIST: "Länge von %1",
    DATA_LISTCONTAINSITEM: "%1 enthält %2?",
    DATA_SHOWLIST: "zeige Liste %1",
    DATA_HIDELIST: "verstecke Liste %1",
    DATA_INDEX_ALL: "alles",
    DATA_INDEX_LAST: "letztes",
    DATA_INDEX_RANDOM: "zufälliges",
    EVENT_WHENFLAGCLICKED: "Wenn %1 angeklickt wird",
    EVENT_WHENTHISSPRITECLICKED: "Wenn diese Figur angeklickt wird",
    EVENT_WHENSTAGECLICKED: "Wenn die Bühne angeklickt wird",
    EVENT_WHENTOUCHINGOBJECT: "Wenn diese Figur %1 berührt",
    EVENT_WHENBROADCASTRECEIVED: "Wenn ich %1 empfange",
    EVENT_WHENBACKDROPSWITCHESTO: "Wenn das Bühnenbild zu %1 wechselt",
    EVENT_WHENGREATERTHAN: "Wenn %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "Stoppuhr",
    EVENT_WHENGREATERTHAN_LOUDNESS: "Lautstärke",
    EVENT_BROADCAST: "sende %1 an alle",
    EVENT_BROADCASTANDWAIT: "sende %1 an alle und warte",
    EVENT_WHENKEYPRESSED: "Wenn Taste %1 gedrückt wird",
    EVENT_WHENKEYPRESSED_SPACE: "Leertaste",
    EVENT_WHENKEYPRESSED_LEFT: "Pfeil nach links",
    EVENT_WHENKEYPRESSED_RIGHT: "Pfeil nach rechts",
    EVENT_WHENKEYPRESSED_DOWN: "Pfeil nach unten",
    EVENT_WHENKEYPRESSED_UP: "Pfeil nach oben",
    EVENT_WHENKEYPRESSED_ANY: "beliebig",
    LOOKS_SAYFORSECS: "sage %1 für %2 Sekunden",
    LOOKS_SAY: "sage %1",
    LOOKS_HELLO: "Hallo!",
    LOOKS_THINKFORSECS: "denke %1 für %2 Sekunden",
    LOOKS_THINK: "denke %1",
    LOOKS_HMM: "Hmm...",
    LOOKS_SHOW: "zeige dich",
    LOOKS_HIDE: "verstecke dich",
    LOOKS_HIDEALLSPRITES: "Alle Figuren verbergen",
    LOOKS_EFFECT_COLOR: "Farbe",
    LOOKS_EFFECT_FISHEYE: "Fischauge",
    LOOKS_EFFECT_WHIRL: "Wirbel",
    LOOKS_EFFECT_PIXELATE: "Pixel",
    LOOKS_EFFECT_MOSAIC: "Mosaik",
    LOOKS_EFFECT_BRIGHTNESS: "Helligkeit",
    LOOKS_EFFECT_GHOST: "Durchsichtigkeit",
    LOOKS_CHANGEEFFECTBY: "ändere Effekt %1 um %2",
    LOOKS_SETEFFECTTO: "setze Effekt %1 auf %2",
    LOOKS_CLEARGRAPHICEFFECTS: "schalte Grafikeffekte aus",
    LOOKS_CHANGESIZEBY: "ändere Größe um %1",
    LOOKS_SETSIZETO: "setze Größe auf %1 %",
    LOOKS_SIZE: "Größe",
    LOOKS_CHANGESTRETCHBY: "ändere Dehnung um %1",
    LOOKS_SETSTRETCHTO: "setze Dehnung auf %1 %",
    LOOKS_SWITCHCOSTUMETO: "wechsle zu Kostüm %1",
    LOOKS_NEXTCOSTUME: "wechsle zum nächsten Kostüm",
    LOOKS_SWITCHBACKDROPTO: "wechsle zu Bühnenbild %1",
    LOOKS_GOTOFRONTBACK: "gehe zur %1 Ebene",
    LOOKS_GOTOFRONTBACK_FRONT: "vorderster",
    LOOKS_GOTOFRONTBACK_BACK: "hinterster",
    LOOKS_GOFORWARDBACKWARDLAYERS: "gehe %2 Ebenen %1",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "nach vorne",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "nach hinten",
    LOOKS_BACKDROPNUMBERNAME: "Bühnenbild %1",
    LOOKS_COSTUMENUMBERNAME: "Kostüm %1",
    LOOKS_NUMBERNAME_NUMBER: "Nummer",
    LOOKS_NUMBERNAME_NAME: "Name",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "wechsle zu Bühnenbild %1 und warte",
    LOOKS_NEXTBACKDROP_BLOCK: "wechsle zum nächsten Bühnenbild",
    LOOKS_NEXTBACKDROP: "nächstes Bühnenbild",
    LOOKS_PREVIOUSBACKDROP: "vorheriges Bühnenbild",
    LOOKS_RANDOMBACKDROP: "zufälliges Bühnenbild",
    MOTION_MOVESTEPS: "gehe %1 Schritte",
    MOTION_TURNLEFT: "drehe dich %1 um %2 Grad",
    MOTION_TURNRIGHT: "drehe dich %1 um %2 Grad",
    MOTION_POINTINDIRECTION: "setze Richtung auf %1 Grad",
    MOTION_POINTTOWARDS: "drehe dich zu %1",
    MOTION_POINTTOWARDS_POINTER: "Mauszeiger",
    MOTION_POINTTOWARDS_RANDOM: "Zufallsrichtung",
    MOTION_GOTO: "gehe zu %1",
    MOTION_GOTO_POINTER: "Mauszeiger",
    MOTION_GOTO_RANDOM: "Zufallsposition",
    MOTION_GOTOXY: "gehe zu x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "gleite in %1 Sek. zu x: %2 y: %3",
    MOTION_GLIDETO: "gleite in %1 Sek. zu %2",
    MOTION_GLIDETO_POINTER: "Mauszeiger",
    MOTION_GLIDETO_RANDOM: "Zufallsposition",
    MOTION_CHANGEXBY: "ändere x um %1",
    MOTION_SETX: "setze x auf %1",
    MOTION_CHANGEYBY: "ändere y um %1",
    MOTION_SETY: "setze y auf %1",
    MOTION_IFONEDGEBOUNCE: "pralle vom Rand ab",
    MOTION_SETROTATIONSTYLE: "setze Drehtyp auf %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "links-rechts",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "nicht drehen",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "rundherum",
    MOTION_XPOSITION: "x-Position",
    MOTION_YPOSITION: "y-Position",
    MOTION_DIRECTION: "Richtung",
    MOTION_SCROLLRIGHT: "%1 nach rechts bewegen",
    MOTION_SCROLLUP: "%1 nach oben bewegen",
    MOTION_ALIGNSCENE: "Szene ausrichten %1",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "unten links",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "unten rechts",
    MOTION_ALIGNSCENE_MIDDLE: "Mitte",
    MOTION_ALIGNSCENE_TOPLEFT: "oben links",
    MOTION_ALIGNSCENE_TOPRIGHT: "oben rechts",
    MOTION_XSCROLL: "x-Bewegung",
    MOTION_YSCROLL: "y-Bewegung",
    MOTION_STAGE_SELECTED: "Bühne ausgewählt: keine Bewegungsblöcke",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "Zufallszahl von %1 bis %2",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 und %2",
    OPERATORS_OR: "%1 oder %2",
    OPERATORS_NOT: "nicht %1",
    OPERATORS_JOIN: "verbinde %1 und %2",
    OPERATORS_JOIN_THREE: "verbinde %1 und %2 und %3",
    OPERATORS_CONSTRAINS: "begrenze %1 auf Min: %2 Max: %3",
    OPERATORS_JOIN_APPLE: "Apfel",
    OPERATORS_JOIN_BANANA: "Banane",
    OPERATORS_LETTEROF: "Zeichen %1 von %2",
    OPERATORS_LETTEROF_APPLE: "a",
    OPERATORS_LENGTH: "Länge von %1",
    OPERATORS_CONTAINS: "%1 enthält %2?",
    OPERATORS_MOD: "%1 mod %2",
    OPERATORS_ROUND: "%1 gerundet",
    OPERATORS_MATHOP: "%1 von %2",
    OPERATORS_MATHOP_ABS: "Betrag",
    OPERATORS_MATHOP_FLOOR: "abrunden",
    OPERATORS_MATHOP_CEILING: "aufrunden",
    OPERATORS_MATHOP_SQRT: "Wurzel",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e^",
    OPERATORS_MATHOP_10EXP: "10^",
    OPERATORS_TOSTRING: "%1 als Zeichenkette",
    PROCEDURES_DEFINITION: "Definiere %1",
    SENSING_TOUCHINGOBJECT: "wird %1 berührt?",
    SENSING_TOUCHINGOBJECT_POINTER: "Mauszeiger",
    SENSING_TOUCHINGOBJECT_EDGE: "Rand",
    SENSING_TOUCHINGCOLOR: "wird Farbe %1 berührt?",
    SENSING_COLORISTOUCHINGCOLOR: "Farbe %1 berührt %2?",
    SENSING_DISTANCETO: "Entfernung von %1",
    SENSING_DISTANCETO_POINTER: "Mauszeiger",
    SENSING_ASKANDWAIT: "frage %1 und warte",
    SENSING_ASK_TEXT: "Wie heißt du?",
    SENSING_ANSWER: "Antwort",
    SENSING_KEYPRESSED: "Taste %1 gedrückt?",
    SENSING_MOUSEDOWN: "Maustaste gedrückt?",
    SENSING_MOUSEX: "Maus x-Position",
    SENSING_MOUSEY: "Maus y-Position",
    SENSING_SETDRAGMODE: "setze Ziehbarkeit auf %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "ziehbar",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "nicht ziehbar",
    SENSING_LOUDNESS: "Lautstärke",
    SENSING_LOUD: "laut?",
    SENSING_TIMER: "Stoppuhr",
    SENSING_RESETTIMER: "setze Stoppuhr zurück",
    SENSING_OF: "%1 von %2",
    SENSING_OF_XPOSITION: "x-Position",
    SENSING_OF_YPOSITION: "y-Position",
    SENSING_OF_DIRECTION: "Richtung",
    SENSING_OF_COSTUMENUMBER: "Kostümnummer",
    SENSING_OF_COSTUMENAME: "Kostümname",
    SENSING_OF_SIZE: "Größe",
    SENSING_OF_VOLUME: "Lautstärke",
    SENSING_OF_BACKDROPNUMBER: "Bühnenbildnummer",
    SENSING_OF_BACKDROPNAME: "Bühnenbildname",
    SENSING_OF_STAGE: "Bühne",
    SENSING_CURRENT: "%1 im Moment",
    SENSING_CURRENT_YEAR: "Jahr",
    SENSING_CURRENT_MONTH: "Monat",
    SENSING_CURRENT_DATE: "Datum",
    SENSING_CURRENT_DAYOFWEEK: "Wochentag",
    SENSING_CURRENT_HOUR: "Stunde",
    SENSING_CURRENT_MINUTE: "Minute",
    SENSING_CURRENT_SECOND: "Sekunde",
    SENSING_DAYSSINCE2000: "Tage seit 2000",
    SENSING_USERNAME: "Benutzername",
    SENSING_USERID: "Benutzer-ID",
    SOUND_PLAY: "spiele Klang %1",
    SOUND_PLAYUNTILDONE: "spiele Klang %1 ganz",
    SOUND_STOPALLSOUNDS: "stoppe alle Klänge",
    SOUND_SETEFFECTO: "setze Effekt %1 auf %2",
    SOUND_CHANGEEFFECTBY: "ändere Effekt %1 um %2",
    SOUND_CLEAREFFECTS: "schalte Klangeffekte aus",
    SOUND_EFFECTS_PITCH: "Tonhöhe",
    SOUND_EFFECTS_PAN: "Balance links/rechts",
    SOUND_CHANGEVOLUMEBY: "ändere Lautstärke um %1",
    SOUND_SETVOLUMETO: "setze Lautstärke auf %1%",
    SOUND_VOLUME: "Lautstärke",
    SOUND_RECORD: "zeichne auf...",
    CATEGORY_MOTION: "Motor",
    CATEGORY_MOVEMENT: "Bewegung",
    CATEGORY_LOOKS: "Anzeige",
    CATEGORY_SOUND: "Klang",
    CATEGORY_EVENTS: "Ereignisse",
    CATEGORY_CONTROL: "Steuerung",
    CATEGORY_SENSING: "Sensoren",
    CATEGORY_OPERATORS: "Operatoren",
    CATEGORY_VARIABLES: "Variablen",
    CATEGORY_MYBLOCKS: "Meine Blöcke",
    DUPLICATE: "Duplizieren",
    DELETE: "Löschen",
    ADD_COMMENT: "Kommentar hinzufügen",
    REMOVE_COMMENT: "Kommentar entfernen",
    DELETE_BLOCK: "Lösche Block",
    DELETE_X_BLOCKS: "Lösche %1 Blöcke",
    DELETE_ALL_BLOCKS: "Alle %1 Blöcke löschen?",
    CLEAN_UP: "Blöcke aufräumen",
    HELP: "Hilfe",
    UNDO: "Rückgängig",
    REDO: "Wiederherstellen",
    EDIT_PROCEDURE: "Bearbeiten",
    SHOW_PROCEDURE_DEFINITION: "Gehe zur Definition",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "Sag etwas...",
    COLOUR_HUE_LABEL: "Farbe",
    COLOUR_SATURATION_LABEL: "Sättigung",
    COLOUR_BRIGHTNESS_LABEL: "Helligkeit",
    CHANGE_VALUE_TITLE: "Wert ändern:",
    RENAME_VARIABLE: "Benenne die Variable um",
    RENAME_VARIABLE_TITLE: "Benenne alle Variablen mit Namen \"%1\" um in:",
    RENAME_VARIABLE_MODAL_TITLE: "Variable umbenennen",
    NEW_VARIABLE: "Neue Variable",
    NEW_VARIABLE_TITLE: "Neuer Variablenname:",
    VARIABLE_MODAL_TITLE: "Neue Variable",
    VARIABLE_ALREADY_EXISTS: "Eine Variable mit dem Namen \"%1\" existiert bereits.",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "Eine Variable mit dem Namen \"%1\" existiert bereits als Variable des Typs \"%2\".",
    DELETE_VARIABLE_CONFIRMATION: "Entferne alle %1 Nutzungen der Variable \"%2\"?",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "Die Variable \"%1\" kann nicht gelöscht werden, weil sie Teil der Definition der Funktion \"%2\" ist.",
    DELETE_VARIABLE: "Lösche die Variable \"%1\"",
    NEW_PROCEDURE: "Neuer Block",
    PROCEDURE_ALREADY_EXISTS: "Eine Prozedur mit dem Namen \"%1\" existiert bereits.",
    PROCEDURE_DEFAULT_NAME: "MeinBlock",
    PROCEDURE_USED: "Bevor die Blockdefinition gelöscht werden kann, muss der Block zuerst aus allen Skripten entfernt werden, in denen er verwendet wird",
    NEW_LIST: "Neue Liste",
    NEW_LIST_TITLE: "Neuer Listenname:",
    LIST_MODAL_TITLE: "Neue Liste",
    LIST_ALREADY_EXISTS: "Eine Liste mit dem Namen \"%1\" existiert bereits",
    RENAME_LIST_TITLE: "Benenne alle Listen mit Namen \"%1\" um in:",
    RENAME_LIST_MODAL_TITLE: "Liste umbenennen",
    DEFAULT_LIST_ITEM: "Ding",
    DELETE_LIST: "Lösche die Liste \"%1\"",
    RENAME_LIST: "Benenne die Liste um",
    NEW_BROADCAST_MESSAGE: "Neue Nachricht",
    NEW_BROADCAST_MESSAGE_TITLE: "Neuer Nachrichtentext:",
    BROADCAST_MODAL_TITLE: "Neue Nachricht",
    DEFAULT_BROADCAST_MESSAGE_NAME: "Nachricht1",
    // Sound category
    NXT_BUZZER_TONE: "spiele Ton mit %1 Hz für %2 Sekunden",
    NXT_BUZZER_NOTE: "spiele Note %1 für %2 Sekunden",
    NXT_BUZZER_STOP: "stoppe alle Klänge",

    // Display category
    NXT_DISP_PRINTCOL: "schreibe %1 in Spalte %2 Zeile %3",
    NXT_DISP_CLEAR: "lösche die Anzeige",

    // Motor category
    NXT_MOTOR_RUNFOR: "%1 drehe %2 %3 mit %4% Geschwindigkeit",
    NXT_MOTOR_ON: "%1 starte Motor mit %2% Geschwindigkeit",
    NXT_MOTOR_OFF: "%1 stoppe Motor",
    NXT_MOTOR_RESET: "%1 setze Gradzähler zurück",
    NXT_MOTOR_DEGREES: "%1 gezählte Grad",

    // Movement category
    NXT_MOVE_SETTING: "setze Antriebsmotoren auf %1 und %2",
    NXT_MOVE_RUNFOR: "fahre %1 %2 mit %3% und %4% Geschwindigkeit",
    NXT_MOVE_ON: "starte Fahrt mit %1% und %2% Geschwindigkeit",
    NXT_MOVE_OFF: "stoppe Fahrt",

    // Sensor category
    NXT_SENSORS_LIGHT_RFL: "%1 Intensität des reflektierten Lichts",
    NXT_SENSORS_LIGHT_AMB: "%1 Intensität des Umgebungslichts",
    NXT_SENSORS_US: "%1 Entfernung in cm",
    NXT_SENSORS_SOUND: "%1 Lautstärke",
    NXT_SENSORS_TOUCH: "%1 gedrückt?",
    NXT_SENSORS_BUTTON: "Taste %1 gedrückt?",
    NXT_SENSORS_TIMER: "Stoppuhr (Sekunden)",
    NXT_SENSORS_TIMER_RESET: "setze Stoppuhr zurück",

    // Dropdown options
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",

    NXT_UNIT_ROTATIONS: "Umdrehungen",
    NXT_UNIT_DEGREES: "Grad",
    NXT_UNIT_SECONDS: "Sekunden",

    NXT_BUTTON_LEFT: "Links",
    NXT_BUTTON_CENTER: "Mitte",
    NXT_BUTTON_RIGHT: "Rechts"
};

Blockly.ScratchMsgs.locales["fr"] = {
    CONTROL_SETUP: "quand le programme démarre",
    CONTROL_FOREVER: "répéter indéfiniment",
    CONTROL_REPEAT: "répéter %1 fois",
    CONTROL_IF: "si %1 alors",
    CONTROL_ELSE: "sinon",
    CONTROL_STOP: "arrêter",
    CONTROL_STOP_ALL: "tout",
    CONTROL_STOP_THIS: "ce script",
    CONTROL_STOP_OTHER: "autres scripts du sprite",
    CONTROL_WAIT: "attendre %1 secondes",
    CONTROL_WAITUNTIL: "attendre jusqu'à ce que %1",
    CONTROL_REPEATUNTIL: "répéter jusqu'à ce que %1",
    CONTROL_WHILE: "tant que %1",
    CONTROL_FOREACH: "pour chaque %1 dans %2",
    CONTROL_STARTASCLONE: "quand je commence comme un clone",
    CONTROL_CREATECLONEOF: "créer un clone de %1",
    CONTROL_CREATECLONEOF_MYSELF: "moi-même",
    CONTROL_DELETETHISCLONE: "supprimer ce clone",
    CONTROL_COUNTER: "compteur",
    CONTROL_INCRCOUNTER: "incrémenter le compteur",
    CONTROL_CLEARCOUNTER: "remettre le compteur à zéro",
    CONTROL_ALLATONCE: "tous en même temps",
    DATA_SETVARIABLETO: "mettre %1 à %2",
    DATA_CHANGEVARIABLEBY: "ajouter %2 à %1",
    DATA_SHOWVARIABLE: "montrer la variable %1",
    DATA_HIDEVARIABLE: "cacher la variable %1",
    DATA_ADDTOLIST: "ajouter %1 à %2",
    DATA_DELETEOFLIST: "supprimer l'élément %1 de %2",
    DATA_DELETEALLOFLIST: "supprimer tous les éléments de la liste %1",
    DATA_INSERTATLIST: "insérer %1 en position %2 de %3",
    DATA_REPLACEITEMOFLIST: "remplacer l'élément %1 de la liste %2 par %3",
    DATA_ITEMOFLIST: "élément %1 de %2",
    DATA_ITEMNUMOFLIST: "position de %1 dans %2",
    DATA_LENGTHOFLIST: "longueur de %1",
    DATA_LISTCONTAINSITEM: "%1 contient %2 ?",
    DATA_SHOWLIST: "montrer la liste %1",
    DATA_HIDELIST: "cacher la liste %1",
    DATA_INDEX_ALL: "tout",
    DATA_INDEX_LAST: "dernier",
    DATA_INDEX_RANDOM: "au hasard",
    EVENT_WHENFLAGCLICKED: "quand %1 est cliqué",
    EVENT_WHENTHISSPRITECLICKED: "quand ce sprite est cliqué",
    EVENT_WHENSTAGECLICKED: "quand la scène est cliquée",
    EVENT_WHENTOUCHINGOBJECT: "quand ce sprite touche %1",
    EVENT_WHENBROADCASTRECEIVED: "quand je reçois %1",
    EVENT_WHENBACKDROPSWITCHESTO: "quand l'arrière-plan bascule sur %1",
    EVENT_WHENGREATERTHAN: "quand le %1 > %2",
    EVENT_WHENGREATERTHAN_TIMER: "chronomètre",
    EVENT_WHENGREATERTHAN_LOUDNESS: "volume sonore",
    EVENT_BROADCAST: "envoyer à tous %1",
    EVENT_BROADCASTANDWAIT: "envoyer à tous %1 et attendre",
    EVENT_WHENKEYPRESSED: "quand la touche %1 est pressée",
    EVENT_WHENKEYPRESSED_SPACE: "espace",
    EVENT_WHENKEYPRESSED_LEFT: "flèche gauche",
    EVENT_WHENKEYPRESSED_RIGHT: "flèche droite",
    EVENT_WHENKEYPRESSED_DOWN: "flèche bas",
    EVENT_WHENKEYPRESSED_UP: "flèche haut",
    EVENT_WHENKEYPRESSED_ANY: "n'importe laquelle",
    LOOKS_SAYFORSECS: "dire %1 pendant %2 secondes",
    LOOKS_SAY: "dire %1",
    LOOKS_HELLO: "Bonjour !",
    LOOKS_THINKFORSECS: "penser à %1 pendant %2 secondes",
    LOOKS_THINK: "penser à %1",
    LOOKS_HMM: "Hmm...",
    LOOKS_SHOW: "montrer",
    LOOKS_HIDE: "cacher",
    LOOKS_HIDEALLSPRITES: "cacher tous les sprites",
    LOOKS_EFFECT_COLOR: "couleur",
    LOOKS_EFFECT_FISHEYE: "œil de poisson",
    LOOKS_EFFECT_WHIRL: "tourbillon",
    LOOKS_EFFECT_PIXELATE: "pixeliser",
    LOOKS_EFFECT_MOSAIC: "mosaïque",
    LOOKS_EFFECT_BRIGHTNESS: "luminosité",
    LOOKS_EFFECT_GHOST: "fantôme",
    LOOKS_CHANGEEFFECTBY: "ajouter %2 à l'effet %1",
    LOOKS_SETEFFECTTO: "mettre l'effet %1 à %2",
    LOOKS_CLEARGRAPHICEFFECTS: "annuler les effets graphiques",
    LOOKS_CHANGESIZEBY: "ajouter %1 à la taille",
    LOOKS_SETSIZETO: "mettre la taille à %1 % de la taille initiale",
    LOOKS_SIZE: "taille",
    LOOKS_CHANGESTRETCHBY: "ajouter %1 à l'étirement",
    LOOKS_SETSTRETCHTO: "mettre l'étirement à %1 %",
    LOOKS_SWITCHCOSTUMETO: "basculer sur le costume %1",
    LOOKS_NEXTCOSTUME: "costume suivant",
    LOOKS_SWITCHBACKDROPTO: "basculer sur l'arrière-plan %1",
    LOOKS_GOTOFRONTBACK: "aller à l'%1 plan",
    LOOKS_GOTOFRONTBACK_FRONT: "avant",
    LOOKS_GOTOFRONTBACK_BACK: "arrière",
    LOOKS_GOFORWARDBACKWARDLAYERS: "déplacer de %2 plans vers l'%1",
    LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD: "avant",
    LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD: "arrière",
    LOOKS_BACKDROPNUMBERNAME: "%1 de l'arrière-plan",
    LOOKS_COSTUMENUMBERNAME: "%1 du costume",
    LOOKS_NUMBERNAME_NUMBER: "numéro",
    LOOKS_NUMBERNAME_NAME: "nom",
    LOOKS_SWITCHBACKDROPTOANDWAIT: "basculer sur l'arrière-plan %1 et attendre",
    LOOKS_NEXTBACKDROP_BLOCK: "arrière-plan suivant",
    LOOKS_NEXTBACKDROP: "arrière-plan suivant",
    LOOKS_PREVIOUSBACKDROP: "arrière-plan précédent",
    LOOKS_RANDOMBACKDROP: "arrière-plan aléatoire",
    MOTION_MOVESTEPS: "avancer de %1 pas",
    MOTION_TURNLEFT: "tourner %1 de %2 degrés",
    MOTION_TURNRIGHT: "tourner %1 de %2 degrés",
    MOTION_POINTINDIRECTION: "s'orienter à %1",
    MOTION_POINTTOWARDS: "s'orienter vers %1",
    MOTION_POINTTOWARDS_POINTER: "pointeur de souris",
    MOTION_POINTTOWARDS_RANDOM: "direction aléatoire",
    MOTION_GOTO: "aller à %1",
    MOTION_GOTO_POINTER: "pointeur de souris",
    MOTION_GOTO_RANDOM: "position aléatoire",
    MOTION_GOTOXY: "aller à x: %1 y: %2",
    MOTION_GLIDESECSTOXY: "glisser en %1 secondes à x: %2 y: %3",
    MOTION_GLIDETO: "glisser en %1 secondes à %2",
    MOTION_GLIDETO_POINTER: "pointeur de souris",
    MOTION_GLIDETO_RANDOM: "position aléatoire",
    MOTION_CHANGEXBY: "ajouter %1 à x",
    MOTION_SETX: "mettre x à %1",
    MOTION_CHANGEYBY: "ajouter %1 à y",
    MOTION_SETY: "mettre y à %1",
    MOTION_IFONEDGEBOUNCE: "rebondir si le bord est atteint",
    MOTION_SETROTATIONSTYLE: "fixer le sens de rotation %1",
    MOTION_SETROTATIONSTYLE_LEFTRIGHT: "gauche-droite",
    MOTION_SETROTATIONSTYLE_DONTROTATE: "ne tourne pas",
    MOTION_SETROTATIONSTYLE_ALLAROUND: "à 360°",
    MOTION_XPOSITION: "abscisse x",
    MOTION_YPOSITION: "ordonnée y",
    MOTION_DIRECTION: "direction",
    MOTION_SCROLLRIGHT: "défiler à droite de %1",
    MOTION_SCROLLUP: "défiler en haut de %1",
    MOTION_ALIGNSCENE: "aligner la scène %1",
    MOTION_ALIGNSCENE_BOTTOMLEFT: "bas-gauche",
    MOTION_ALIGNSCENE_BOTTOMRIGHT: "bas-droite",
    MOTION_ALIGNSCENE_MIDDLE: "milieu",
    MOTION_ALIGNSCENE_TOPLEFT: "haut-gauche",
    MOTION_ALIGNSCENE_TOPRIGHT: "haut-droite",
    MOTION_XSCROLL: "défilement x",
    MOTION_YSCROLL: "défilement y",
    MOTION_STAGE_SELECTED: "Scène sélectionnée : aucun bloc de mouvement",
    OPERATORS_ADD: "%1 + %2",
    OPERATORS_SUBTRACT: "%1 - %2",
    OPERATORS_MULTIPLY: "%1 * %2",
    OPERATORS_DIVIDE: "%1 / %2",
    OPERATORS_RANDOM: "nombre aléatoire entre %1 et %2",
    OPERATORS_GT: "%1 > %2",
    OPERATORS_LT: "%1 < %2",
    OPERATORS_EQUALS: "%1 = %2",
    OPERATORS_AND: "%1 et %2",
    OPERATORS_OR: "%1 ou %2",
    OPERATORS_NOT: "non %1",
    OPERATORS_JOIN: "regrouper %1 et %2",
    OPERATORS_JOIN_THREE: "regrouper %1 et %2 et %3",
    OPERATORS_CONSTRAINS: "limiter %1 entre min : %2 et max : %3",
    OPERATORS_JOIN_APPLE: "pomme",
    OPERATORS_JOIN_BANANA: "banane",
    OPERATORS_LETTEROF: "lettre %1 de %2",
    OPERATORS_LETTEROF_APPLE: "p",
    OPERATORS_LENGTH: "longueur de %1",
    OPERATORS_CONTAINS: "%1 contient %2 ?",
    OPERATORS_MOD: "%1 modulo %2",
    OPERATORS_ROUND: "arrondi de %1",
    OPERATORS_MATHOP: "%1 de %2",
    OPERATORS_MATHOP_ABS: "abs",
    OPERATORS_MATHOP_FLOOR: "plancher",
    OPERATORS_MATHOP_CEILING: "plafond",
    OPERATORS_MATHOP_SQRT: "racine",
    OPERATORS_MATHOP_SIN: "sin",
    OPERATORS_MATHOP_COS: "cos",
    OPERATORS_MATHOP_TAN: "tan",
    OPERATORS_MATHOP_ASIN: "asin",
    OPERATORS_MATHOP_ACOS: "acos",
    OPERATORS_MATHOP_ATAN: "atan",
    OPERATORS_MATHOP_LN: "ln",
    OPERATORS_MATHOP_LOG: "log",
    OPERATORS_MATHOP_EEXP: "e^",
    OPERATORS_MATHOP_10EXP: "10^",
    OPERATORS_TOSTRING: "%1 en chaîne de caractères",
    PROCEDURES_DEFINITION: "définir %1",
    SENSING_TOUCHINGOBJECT: "touche le %1 ?",
    SENSING_TOUCHINGOBJECT_POINTER: "pointeur de souris",
    SENSING_TOUCHINGOBJECT_EDGE: "bord",
    SENSING_TOUCHINGCOLOR: "couleur %1 touchée ?",
    SENSING_COLORISTOUCHINGCOLOR: "couleur %1 touche %2 ?",
    SENSING_DISTANCETO: "distance de %1",
    SENSING_DISTANCETO_POINTER: "pointeur de souris",
    SENSING_ASKANDWAIT: "demander %1 et attendre",
    SENSING_ASK_TEXT: "Quel est ton nom ?",
    SENSING_ANSWER: "réponse",
    SENSING_KEYPRESSED: "touche %1 pressée ?",
    SENSING_MOUSEDOWN: "souris pressée ?",
    SENSING_MOUSEX: "souris x",
    SENSING_MOUSEY: "souris y",
    SENSING_SETDRAGMODE: "mettre mode de glissement à %1",
    SENSING_SETDRAGMODE_DRAGGABLE: "glissable",
    SENSING_SETDRAGMODE_NOTDRAGGABLE: "non glissable",
    SENSING_LOUDNESS: "volume sonore",
    SENSING_LOUD: "fort ?",
    SENSING_TIMER: "chronomètre",
    SENSING_RESETTIMER: "réinitialiser le chronomètre",
    SENSING_OF: "%1 de %2",
    SENSING_OF_XPOSITION: "abscisse x",
    SENSING_OF_YPOSITION: "ordonnée y",
    SENSING_OF_DIRECTION: "direction",
    SENSING_OF_COSTUMENUMBER: "numéro de costume",
    SENSING_OF_COSTUMENAME: "nom du costume",
    SENSING_OF_SIZE: "taille",
    SENSING_OF_VOLUME: "volume",
    SENSING_OF_BACKDROPNUMBER: "numéro de l'arrière-plan",
    SENSING_OF_BACKDROPNAME: "nom de l'arrière-plan",
    SENSING_OF_STAGE: "la scène",
    SENSING_CURRENT: "%1 en cours",
    SENSING_CURRENT_YEAR: "année",
    SENSING_CURRENT_MONTH: "mois",
    SENSING_CURRENT_DATE: "date",
    SENSING_CURRENT_DAYOFWEEK: "jour de la semaine",
    SENSING_CURRENT_HOUR: "heure",
    SENSING_CURRENT_MINUTE: "minute",
    SENSING_CURRENT_SECOND: "seconde",
    SENSING_DAYSSINCE2000: "jours depuis 2000",
    SENSING_USERNAME: "nom d'utilisateur",
    SENSING_USERID: "id de l'utilisateur",
    SOUND_PLAY: "jouer le son %1",
    SOUND_PLAYUNTILDONE: "jouer le son %1 jusqu'au bout",
    SOUND_STOPALLSOUNDS: "arrêter tous les sons",
    SOUND_SETEFFECTO: "mettre l'effet %1 à %2",
    SOUND_CHANGEEFFECTBY: "ajouter %2 à l'effet %1",
    SOUND_CLEAREFFECTS: "annuler tous les effets sonores",
    SOUND_EFFECTS_PITCH: "hauteur",
    SOUND_EFFECTS_PAN: "stéréo gauche/droite",
    SOUND_CHANGEVOLUMEBY: "ajouter %1 au volume",
    SOUND_SETVOLUMETO: "mettre le volume à %1%",
    SOUND_VOLUME: "volume",
    SOUND_RECORD: "enregistrer...",
    CATEGORY_MOTION: "Moteur",
    CATEGORY_MOVEMENT: "Déplacement",
    CATEGORY_LOOKS: "Affichage",
    CATEGORY_SOUND: "Son",
    CATEGORY_EVENTS: "Événements",
    CATEGORY_CONTROL: "Contrôle",
    CATEGORY_SENSING: "Capteurs",
    CATEGORY_OPERATORS: "Opérateurs",
    CATEGORY_VARIABLES: "Variables",
    CATEGORY_MYBLOCKS: "Mes blocs",
    DUPLICATE: "Dupliquer",
    DELETE: "Supprimer",
    ADD_COMMENT: "Ajouter un commentaire",
    REMOVE_COMMENT: "Retirer le commentaire",
    DELETE_BLOCK: "Supprimer le bloc",
    DELETE_X_BLOCKS: "Supprimer %1 blocs",
    DELETE_ALL_BLOCKS: "Supprimer tous les %1 blocs ?",
    CLEAN_UP: "Organiser les blocs",
    HELP: "Aide",
    UNDO: "Annuler",
    REDO: "Rétablir",
    EDIT_PROCEDURE: "Modifier",
    SHOW_PROCEDURE_DEFINITION: "Aller à la définition",
    WORKSPACE_COMMENT_DEFAULT_TEXT: "Dire quelque chose...",
    COLOUR_HUE_LABEL: "Couleur",
    COLOUR_SATURATION_LABEL: "Saturation",
    COLOUR_BRIGHTNESS_LABEL: "Luminosité",
    CHANGE_VALUE_TITLE: "Changer la valeur :",
    RENAME_VARIABLE: "Renommer la variable",
    RENAME_VARIABLE_TITLE: "Renommer toutes les variables \"%1\" en :",
    RENAME_VARIABLE_MODAL_TITLE: "Renommer la variable",
    NEW_VARIABLE: "Créer une variable",
    NEW_VARIABLE_TITLE: "Nom de la nouvelle variable :",
    VARIABLE_MODAL_TITLE: "Nouvelle variable",
    VARIABLE_ALREADY_EXISTS: "Une variable nommée \"%1\" existe déjà.",
    VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: "Une variable nommée \"%1\" existe déjà pour une autre variable de type \"%2\".",
    DELETE_VARIABLE_CONFIRMATION: "Supprimer %1 utilisations de la variable \"%2\" ?",
    CANNOT_DELETE_VARIABLE_PROCEDURE: "Impossible de supprimer la variable \"%1\" car elle fait partie de la définition de la fonction \"%2\"",
    DELETE_VARIABLE: "Supprimer la variable \"%1\"",
    NEW_PROCEDURE: "Créer un bloc",
    PROCEDURE_ALREADY_EXISTS: "Une procédure nommée \"%1\" existe déjà.",
    PROCEDURE_DEFAULT_NAME: "MonBloc",
    PROCEDURE_USED: "Pour supprimer la définition d'un bloc, supprimez d'abord toutes les utilisations de ce bloc",
    NEW_LIST: "Créer une liste",
    NEW_LIST_TITLE: "Nom de la nouvelle liste :",
    LIST_MODAL_TITLE: "Nouvelle liste",
    LIST_ALREADY_EXISTS: "Une liste nommée \"%1\" existe déjà.",
    RENAME_LIST_TITLE: "Renommer toutes les listes \"%1\" en :",
    RENAME_LIST_MODAL_TITLE: "Renommer la liste",
    DEFAULT_LIST_ITEM: "chose",
    DELETE_LIST: "Supprimer la liste \"%1\"",
    RENAME_LIST: "Renommer la liste",
    NEW_BROADCAST_MESSAGE: "Nouveau message",
    NEW_BROADCAST_MESSAGE_TITLE: "Nom du nouveau message :",
    BROADCAST_MODAL_TITLE: "Nouveau message",
    DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
    // Sound category
    NXT_BUZZER_TONE: "jouer un bip à %1 Hz pendant %2 secondes",
    NXT_BUZZER_NOTE: "jouer la note %1 pendant %2 secondes",
    NXT_BUZZER_STOP: "arrêter tous les sons",

    // Display category
    NXT_DISP_PRINTCOL: "écrire %1 à la colonne %2 ligne %3",
    NXT_DISP_CLEAR: "effacer l’écran",

    // Motor category
    NXT_MOTOR_RUNFOR: "%1 faire tourner sur %2 %3 à %4% de vitesse",
    NXT_MOTOR_ON: "%1 démarrer le moteur à %2% de vitesse",
    NXT_MOTOR_OFF: "%1 arrêter le moteur",
    NXT_MOTOR_RESET: "%1 remettre le compteur de degrés à zéro",
    NXT_MOTOR_DEGREES: "%1 degrés comptés",

    // Movement category
    NXT_MOVE_SETTING: "définir les moteurs de déplacement sur %1 et %2",
    NXT_MOVE_RUNFOR: "se déplacer sur %1 %2 aux vitesses de %3% et %4%",
    NXT_MOVE_ON: "commencer à se déplacer aux vitesses de %1% et %2%",
    NXT_MOVE_OFF: "arrêter le déplacement",

    // Sensor category
    NXT_SENSORS_LIGHT_RFL: "%1 intensité de la lumière réfléchie",
    NXT_SENSORS_LIGHT_AMB: "%1 intensité de la lumière ambiante",
    NXT_SENSORS_US: "%1 distance en cm",
    NXT_SENSORS_SOUND: "%1 niveau sonore",
    NXT_SENSORS_TOUCH: "%1 est pressé ?",
    NXT_SENSORS_BUTTON: "le bouton %1 est pressé ?",
    NXT_SENSORS_TIMER: "chronomètre (secondes)",
    NXT_SENSORS_TIMER_RESET: "réinitialiser le chronomètre",

    // Dropdown options
    NXT_NOTE_C4: "C4",
    NXT_NOTE_D4: "D4",
    NXT_NOTE_E4: "E4",
    NXT_NOTE_F4: "F4",
    NXT_NOTE_G4: "G4",
    NXT_NOTE_A4: "A4",
    NXT_NOTE_B4: "B4",
    NXT_NOTE_C5: "C5",
    NXT_NOTE_D5: "D5",
    NXT_NOTE_E5: "E5",
    NXT_NOTE_F5: "F5",
    NXT_NOTE_G5: "G5",
    NXT_NOTE_A5: "A5",
    NXT_NOTE_B5: "B5",
    NXT_NOTE_C6: "C6",

    NXT_UNIT_ROTATIONS: "rotations",
    NXT_UNIT_DEGREES: "degrés",
    NXT_UNIT_SECONDS: "secondes",

    NXT_BUTTON_LEFT: "Gauche",
    NXT_BUTTON_CENTER: "Centre",
    NXT_BUTTON_RIGHT: "Droite"
};
